"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { authenticatedFetch } from "@/app/lib/authenticated-fetch";
import { getCurrentProfile } from "@/app/lib/auth";

type Item = { created_at: string; school_id: number | null; school_name: string; actor_name: string; actor_role: string; action_label: string; module: string; target_type: string | null };
type School = { id: number; school_name: string };
const modules = ["", "Registration", "Requirements", "Documents & Evidence", "Staff Compliance", "Inspections", "Corrective Actions", "Certificates & Renewals"];
export default function ComplianceActivityPage() {
  const router = useRouter(); const [items, setItems] = useState<Item[]>([]); const [schools, setSchools] = useState<School[]>([]); const [page, setPage] = useState(0); const [more, setMore] = useState(false); const [actor, setActor] = useState(""); const [school, setSchool] = useState(""); const [module, setModule] = useState(""); const [from, setFrom] = useState(""); const [to, setTo] = useState(""); const [loading, setLoading] = useState(true);
  const load = async (nextPage = 0) => { setLoading(true); const query = new URLSearchParams({ page: String(nextPage) }); if (actor) query.set("actor", actor); if (school) query.set("school_id", school); if (module) query.set("module", module); if (from) query.set("from", from); if (to) query.set("to", to); const response = await authenticatedFetch(`/api/master/compliance-activity?${query}`); const body = await response.json(); if (!response.ok) { alert(body.error || "Compliance activity could not be loaded."); setLoading(false); return; } setItems(body.items || []); setSchools(body.schools || []); setPage(nextPage); setMore(Boolean(body.has_more)); setLoading(false); };
  useEffect(() => { void (async () => { const { profile } = await getCurrentProfile(); if (!profile || (profile.role !== "master" && profile.platform_role !== "master_admin")) { router.replace("/dashboard"); return; } await load(); })(); }, []);
  return <main><section className="db-soft-card" style={{ padding: 18, marginBottom: 14 }}><p style={{ margin: 0, fontWeight: 800, color: "#6D6888" }}>MASTER OVERSIGHT</p><h1 className="db-page-title">Compliance Activity</h1><p className="db-page-subtitle">Read-only audit history for recorded compliance work across DailyBloom schools.</p></section><section className="db-card" style={{ padding: 16 }}><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(170px,1fr))", gap: 8 }}><label>School<select className="db-input" value={school} onChange={(e) => setSchool(e.target.value)}><option value="">All schools</option>{schools.map((item) => <option key={item.id} value={item.id}>{item.school_name}</option>)}</select></label><label>Actor<input className="db-input" value={actor} onChange={(e) => setActor(e.target.value)} /></label><label>Compliance area<select className="db-input" value={module} onChange={(e) => setModule(e.target.value)}>{modules.map((value) => <option key={value} value={value}>{value || "All areas"}</option>)}</select></label><label>From<input className="db-input" type="date" value={from} onChange={(e) => setFrom(e.target.value)} /></label><label>To<input className="db-input" type="date" value={to} onChange={(e) => setTo(e.target.value)} /></label></div><button className="db-button-primary" style={{ marginTop: 12 }} onClick={() => void load()}>Apply filters</button></section><section className="db-card" style={{ padding: 16, marginTop: 14 }}><h2 style={{ marginTop: 0 }}>Audit history</h2>{loading ? <p className="db-helper">Loading activity…</p> : items.length ? <div style={{ display: "grid", gap: 9 }}>{items.map((item, index) => <article className="db-list-card" key={`${item.created_at}-${index}`}><strong>{item.action_label}</strong><p className="db-helper" style={{ margin: "5px 0" }}>{item.module} · {item.actor_name} ({item.actor_role})</p><p className="db-helper" style={{ margin: 0 }}>{new Intl.DateTimeFormat("en-ZA", { dateStyle: "medium", timeStyle: "short" }).format(new Date(item.created_at))} · {item.school_id ? <Link href={`/dbe-registration/overview?school=${item.school_id}`}>{item.school_name}</Link> : item.school_name}{item.target_type ? ` · ${item.target_type.replaceAll("_", " ")}` : ""}</p></article>)}</div> : <p className="db-helper">No compliance activity matches these filters.</p>}{more ? <button className="db-button-secondary" style={{ marginTop: 12 }} onClick={() => void load(page + 1)}>Load more</button> : null}</section></main>;
}
