export const PERMISSIONS = {
  STAFF_VIEW: "staff.view",
  STAFF_MANAGE: "staff.manage",
  CLASSROOM_ASSIGN: "classrooms.assign_staff",
  SCHOOL_MANAGE: "school.manage",
  SCHOOL_ONBOARD: "platform.schools.onboard",
  SCHOOL_STATUS: "platform.schools.status",
  PRINCIPAL_MANAGE: "platform.principals.manage",
  MESSAGE_SEND: "messages.send",
  MESSAGE_VIEW: "messages.view",
  PARENT_NOTIFY: "parents.notify",
  PARENT_ACCESS_MANAGE: "parents.access.manage",
  REQUIREMENTS_VIEW: "requirements.view",
  REQUIREMENTS_TRACK: "requirements.track",
  REQUIREMENTS_MANAGE: "requirements.manage",
  INCIDENT_REVIEW: "incidents.review",
  SAFEGUARDING_VIEW: "incidents.safeguarding_view",
  BILLING_MANAGE: "billing.manage",
  PLATFORM_ADMIN_MANAGE: "platform.admins.manage",
} as const;

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];

export const ROLE_PERMISSIONS: Record<string, readonly Permission[]> = {
  master: Object.values(PERMISSIONS),
  master_admin: [PERMISSIONS.STAFF_VIEW, PERMISSIONS.SCHOOL_ONBOARD, PERMISSIONS.SCHOOL_STATUS, PERMISSIONS.PRINCIPAL_MANAGE, PERMISSIONS.MESSAGE_SEND, PERMISSIONS.MESSAGE_VIEW, PERMISSIONS.PARENT_NOTIFY, PERMISSIONS.BILLING_MANAGE, PERMISSIONS.REQUIREMENTS_VIEW],
  owner: [PERMISSIONS.STAFF_VIEW, PERMISSIONS.STAFF_MANAGE, PERMISSIONS.CLASSROOM_ASSIGN, PERMISSIONS.SCHOOL_MANAGE, PERMISSIONS.MESSAGE_SEND, PERMISSIONS.MESSAGE_VIEW, PERMISSIONS.PARENT_NOTIFY, PERMISSIONS.PARENT_ACCESS_MANAGE, PERMISSIONS.REQUIREMENTS_VIEW, PERMISSIONS.REQUIREMENTS_TRACK, PERMISSIONS.REQUIREMENTS_MANAGE, PERMISSIONS.INCIDENT_REVIEW, PERMISSIONS.BILLING_MANAGE],
  principal: [PERMISSIONS.STAFF_VIEW, PERMISSIONS.STAFF_MANAGE, PERMISSIONS.CLASSROOM_ASSIGN, PERMISSIONS.SCHOOL_MANAGE, PERMISSIONS.MESSAGE_SEND, PERMISSIONS.MESSAGE_VIEW, PERMISSIONS.PARENT_NOTIFY, PERMISSIONS.PARENT_ACCESS_MANAGE, PERMISSIONS.REQUIREMENTS_VIEW, PERMISSIONS.REQUIREMENTS_TRACK, PERMISSIONS.REQUIREMENTS_MANAGE, PERMISSIONS.INCIDENT_REVIEW, PERMISSIONS.SAFEGUARDING_VIEW, PERMISSIONS.BILLING_MANAGE],
  admin: [PERMISSIONS.STAFF_VIEW, PERMISSIONS.CLASSROOM_ASSIGN, PERMISSIONS.MESSAGE_SEND, PERMISSIONS.MESSAGE_VIEW, PERMISSIONS.PARENT_NOTIFY, PERMISSIONS.PARENT_ACCESS_MANAGE, PERMISSIONS.REQUIREMENTS_VIEW, PERMISSIONS.REQUIREMENTS_TRACK, PERMISSIONS.REQUIREMENTS_MANAGE],
  teacher: [PERMISSIONS.MESSAGE_SEND, PERMISSIONS.MESSAGE_VIEW, PERMISSIONS.PARENT_NOTIFY, PERMISSIONS.REQUIREMENTS_VIEW, PERMISSIONS.REQUIREMENTS_TRACK],
};
