"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { getCurrentProfile } from "@/app/lib/auth";
import { resolveSchoolContext } from "@/app/lib/school-context";
import { authenticatedFetch } from "@/app/lib/authenticated-fetch";
import { ComplianceHeader, formatComplianceDate } from "../components";
import { READY_EXPLANATION, nextRequirementAction } from "@/app/lib/compliance-guidance";

type Row = Record<string, unknown>;
type ChecklistStatus = "Not Yet" | "Partly Ready" | "Ready" | "Not Applicable";
type Entry = { key: string; label: string; note?: string };
type Section = { title: string; items: Entry[] };

const checklistStatuses: ChecklistStatus[] = ["Not Yet", "Partly Ready", "Ready", "Not Applicable"];
const urgent = new Set(["Missing", "Needs Review", "Expired"]);
const item = (key: string, label: string, note?: string): Entry => ({ key, label, note });

const checklists: Record<string, Section[]> = {
  "Health and safety self-assessment": [
    { title: "Site assessment", items: [item("site-self-assessment", "Current health and safety self-assessment"), item("site-actions", "Actions identified by the assessment have been recorded")] },
    { title: "Health records", items: [
      item("municipal-health-clearance", "Municipal environmental health certificate or clearance", "Use the document issued or requested by the municipality."),
      item("health-care-policy", "Health-care and sick-child policy"), item("safe-water", "Safe drinking-water arrangements"),
      item("toilets-hygiene", "Hygienic toilets and hand-washing arrangements"), item("refuse-disposal", "Refuse storage and disposal arrangements"),
    ] },
    { title: "Food safety", items: [item("food-area", "Hygienic food preparation and storage area", "Use Not Applicable only when food is not prepared or handled."), item("food-certificate", "Food-premises certificate or Certificate of Acceptability, where locally required")] },
    { title: "Fire and emergencies", items: [item("fire-clearance", "Fire and safety clearance, where required locally"), item("emergency-plan", "Written emergency and evacuation plan"), item("emergency-contacts", "Emergency contacts and procedures available to staff"), item("evacuation-practice", "Evacuation practice or drill record", "DailyBloom preparation guidance; confirm the local expectation.")] },
    { title: "Premises", items: [item("land-use", "Zoning, consent-use or right-of-use record, where applicable"), item("building-plans", "Approved or submitted building plans, where applicable"), item("space-ventilation", "Adequate space and ventilation"), item("hazardous-storage", "Safe storage for medicines, chemicals and hazardous items"), item("age-separation", "Suitable arrangements for separating age groups"), item("accessibility", "Accessibility arrangements for children with disabilities, where applicable")] },
  ],
  "Official application preparation": [
    { title: "Application information", items: [item("application-form", "Current application form or online application information"), item("applicant-details", "Applicant identity and contact details"), item("facility-address", "Physical and postal address"), item("children-capacity", "Number and ages of children to be accommodated"), item("programme-description", "Programme description, aims and objectives"), item("official-reference", "Official application or registration reference, once issued")] },
    { title: "Organisation records", items: [item("business-plan", "Business plan covering hours, fees, daily programme and staff composition"), item("constitution-entity", "Constitution or entity registration record, where applicable"), item("management-details", "Management structure, powers and responsibilities")] },
    { title: "Supporting documents", items: [item("application-building-plan", "Building-plan evidence, where applicable"), item("application-emergency-plan", "Emergency plan"), item("application-health-certificate", "Municipal health certificate or clearance"), item("application-staff-clearances", "Required individual staff clearance records")] },
  ],
  "Agreement and conditions acknowledgement": [
    { title: "Acknowledgements", items: [item("conditions-acknowledgement", "Signed acknowledgement of registration conditions, where provided"), item("parent-agreement", "Parent or caregiver agreement used by the school")] },
    { title: "Policies", items: [item("child-protection-policy", "Child-protection policy"), item("discipline-policy", "Discipline and behaviour-management policy"), item("complaints-policy", "Complaints and incident-escalation procedure")] },
  ],
  "Staff supporting information": [
    { title: "Staff directory", items: [item("current-staff-list", "Current staff list with each person’s role"), item("staff-identities", "Identity document recorded for each staff member"), item("staff-qualifications", "Qualifications, skills and experience records, where applicable")] },
    { title: "Individual screening", items: [item("form-30", "Form 30 or National Child Protection Register check for each relevant person"), item("other-clearance", "Other individual clearance evidence requested by the relevant authority"), item("screening-dates", "Issue, verification or expiry dates recorded against each person")] },
  ],
};

const category = (row: Row) => String(row.requirement_category || row.requirement_group || "Other").replaceAll("_", " ");
const sectionsFor = (row: Row): Section[] => checklists[String(row.title)] || [{ title: "Preparation", items: [item("supporting-information", String(row.preparation_guidance || row.what_to_prepare || "Supporting information and evidence that apply"))] }];
const savedChecklist = (state?: Row) => state?.checklist_state && typeof state.checklist_state === "object" ? state.checklist_state as Record<string, ChecklistStatus> : {};
function progressFor(requirement: Row, state?: Row) {
  const values = sectionsFor(requirement).flatMap((section) => section.items).map((entry) => savedChecklist(state)[entry.key] || "Not Yet");
  const considered = values.filter((value) => value !== "Not Applicable"); const ready = considered.filter((value) => value === "Ready").length;
  if (!considered.length) return { status: "Not Applicable", ready: 0, total: 0 };
  if (ready === considered.length) return { status: "Ready", ready, total: considered.length };
  if (values.some((value) => value === "Ready" || value === "Partly Ready")) return { status: "In Progress", ready, total: considered.length };
  return { status: String(state?.status || "Not Started"), ready, total: considered.length };
}
const statusLabel = (status: string) => ({ "Not Started": "Not started", "In Progress": "In progress", Ready: "Prepared in DailyBloom", "Needs Review": "Needs review", Missing: "Needs attention", Expired: "Expired", "Not Applicable": "Not applicable" }[status] || status);
const sourceDetails = (row: Row) => row.authority_type === "dailybloom_guidance" || !row.authority_name
  ? { source: "DailyBloom Guidance", applies: "Guidance only", detail: String(row.source_title || "DailyBloom registration-readiness guidance") }
  : { source: String(row.authority_name), applies: row.applicability_scope === "needs_review" || !row.applicability_scope ? "Applicability needs confirmation" : String(row.province || row.applicability_scope).replaceAll("_", " "), detail: String(row.source_title || "Confirm source details with the relevant authority.") };

export default function RequirementsPage() {
  const router = useRouter(); const params = useSearchParams(); const [school, setSchool] = useState<number>();
  const [catalogue, setCatalogue] = useState<Row[]>([]); const [states, setStates] = useState<Row[]>([]); const [documents, setDocuments] = useState<Row[]>([]); const [links, setLinks] = useState<Row[]>([]);
  const [filter, setFilter] = useState("All"); const [search, setSearch] = useState(""); const [savingItem, setSavingItem] = useState("");
  const load = async (id: number) => { const responses = await Promise.all([authenticatedFetch(`/api/compliance?school_id=${id}&resource=catalogue`), authenticatedFetch(`/api/compliance?school_id=${id}&resource=requirements`), authenticatedFetch(`/api/dbe-compliance-documents?school_id=${id}`), authenticatedFetch(`/api/compliance?school_id=${id}&resource=evidence`)]); if (!responses.every((response) => response.ok)) { alert("Requirements could not be loaded."); return; } const [a, b, c, d] = await Promise.all(responses.map((response) => response.json())); setCatalogue(a.items || []); setStates(b.items || []); setDocuments(c.documents || []); setLinks(d.items || []); };
  useEffect(() => { void (async () => { const { profile } = await getCurrentProfile(); if (!profile || profile.role === "teacher") { router.replace(profile ? "/teacher" : "/login"); return; } const context = await resolveSchoolContext(params.get("school")); if (!context.schoolId) { router.replace("/login"); return; } setSchool(context.schoolId); await load(context.schoolId); })(); }, [params, router]);
  const stateFor = (id: string) => states.find((row) => row.requirement_id === id); const evidenceFor = (state?: Row) => state ? links.filter((row) => row.school_requirement_id === state.id) : [];
  const groups = useMemo(() => [...new Set(catalogue.map(category))].sort(), [catalogue]);
  const selected = catalogue.filter((row) => { const progress = progressFor(row, stateFor(String(row.id))); return (!search || String(row.plain_language_title || row.title).toLowerCase().includes(search.toLowerCase())) && (filter === "All" || filter === "Needs Attention" && urgent.has(progress.status) || filter === "In Progress" && progress.status === "In Progress" || filter === "Prepared" && progress.status === "Ready" || filter === "Not Applicable" && progress.status === "Not Applicable"); });
  const saveChecklistItem = async (requirementId: string, itemKey: string, status: ChecklistStatus) => { if (!school) return; setSavingItem(`${requirementId}:${itemKey}`); const response = await authenticatedFetch("/api/compliance", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "save_checklist_item", school_id: school, requirement_id: requirementId, item_key: itemKey, status }) }); setSavingItem(""); if (!response.ok) alert((await response.json()).error || "Could not save checklist item."); else await load(school); };
  const saveDetails = async (requirement: Row, form: HTMLFormElement) => { if (!school) return; const fields = new FormData(form); const progress = progressFor(requirement, stateFor(String(requirement.id))); const response = await authenticatedFetch("/api/compliance", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "save_requirement", school_id: school, requirement_id: requirement.id, status: progress.status, notes: fields.get("notes"), expires_at: fields.get("expires_at"), verify: fields.get("verify") === "on" }) }); if (!response.ok) alert((await response.json()).error || "Could not save details."); else await load(school); };
  const linkEvidence = async (stateId: string, documentId: string) => { if (!school) return; const response = await authenticatedFetch("/api/compliance", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "link_evidence", school_id: school, school_requirement_id: stateId, document_id: documentId }) }); if (!response.ok) alert((await response.json()).error || "Could not link evidence."); else await load(school); };
  if (!school) return <p>Loading requirements…</p>;
  const allProgress = catalogue.map((row) => progressFor(row, stateFor(String(row.id)))); const applicable = allProgress.filter((row) => row.status !== "Not Applicable");
  return <div><ComplianceHeader title="Requirements" description="Work through each preparation checklist and keep supporting records together." />
    <section className="db-card db-card-blue" style={{ padding: 16, marginBottom: 14 }}><h3 style={{ margin: 0 }}>Requirements at a glance</h3><p className="db-helper">{applicable.length} applicable items · {applicable.filter((row) => row.status === "Ready").length} prepared · {applicable.filter((row) => urgent.has(row.status)).length} need attention</p><details><summary style={{ cursor: "pointer", fontWeight: 700 }}>How requirements work</summary><p className="db-helper">These preparation checklists organise information and evidence. They do not replace current DBE, DSD, municipal or other authority requirements.</p></details></section>
    <section><p className="db-helper">Open a category, then open a requirement to record each item as Not Yet, Partly Ready, Ready or Not Applicable.</p><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(160px,1fr))", gap: 8, marginBottom: 12 }}><input className="db-input" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search checklist" aria-label="Search requirements" /><select className="db-input" value={filter} onChange={(event) => setFilter(event.target.value)} aria-label="Filter requirements"><option>All</option><option>Needs Attention</option><option>In Progress</option><option>Prepared</option><option>Not Applicable</option></select></div><div style={{ borderTop: "1px solid #E9E0D8" }}>{groups.map((name) => { const rows = selected.filter((row) => category(row) === name); if (!rows.length) return null; const categoryProgress = rows.map((row) => progressFor(row, stateFor(String(row.id)))); return <details key={name} style={{ borderBottom: "1px solid #E9E0D8", background: "white" }}><summary style={{ cursor: "pointer", listStyle: "none", padding: "14px 4px", display: "flex", justifyContent: "space-between", alignItems: "center", gap: 12 }}><span><strong>{name}</strong><small className="db-helper" style={{ display: "block", margin: "3px 0 0" }}>{rows.length} requirement{rows.length === 1 ? "" : "s"} · {categoryProgress.filter((item) => item.status === "Ready").length} prepared</small></span><small style={{ fontWeight: 700 }}>Checklist · Details</small></summary><div style={{ paddingLeft: 14, borderTop: "1px solid #F1EAE4" }}>{rows.map((row) => <RequirementRow key={String(row.id)} requirement={row} state={stateFor(String(row.id))} evidence={evidenceFor(stateFor(String(row.id)))} documents={documents} savingItem={savingItem} saveChecklistItem={saveChecklistItem} saveDetails={saveDetails} linkEvidence={linkEvidence} school={school} />)}</div></details>; })}</div>{!selected.length ? <p className="db-helper">No requirements currently match this filter.</p> : null}</section>
  </div>;
}

function RequirementRow({ requirement, state, evidence, documents, savingItem, saveChecklistItem, saveDetails, linkEvidence, school }: { requirement: Row; state?: Row; evidence: Row[]; documents: Row[]; savingItem: string; saveChecklistItem: (requirementId: string, itemKey: string, status: ChecklistStatus) => Promise<void>; saveDetails: (requirement: Row, form: HTMLFormElement) => Promise<void>; linkEvidence: (stateId: string, documentId: string) => Promise<void>; school: number }) {
  const progress = progressFor(requirement, state); const saved = savedChecklist(state); const source = sourceDetails(requirement);
  return <details style={{ borderBottom: "1px solid #E9E0D8", background: "white" }}><summary style={{ cursor: "pointer", listStyle: "none", padding: "13px 4px", display: "flex", justifyContent: "space-between", alignItems: "center", gap: 12 }}><span style={{ display: "flex", alignItems: "center", gap: 10 }}><span style={{ width: 21, height: 21, borderRadius: 6, border: `2px solid ${progress.status === "Ready" ? "#3C9B66" : "#CFC7BE"}`, background: progress.status === "Ready" ? "#EAF8EF" : "#FFFDFB", color: "#277047", display: "inline-grid", placeItems: "center", fontWeight: 800 }}>{progress.status === "Ready" ? "✓" : ""}</span><span><strong>{String(requirement.plain_language_title || requirement.title)}</strong><small className="db-helper" style={{ display: "block", margin: 0 }}>{progress.ready} of {progress.total} ready</small></span></span><small style={{ fontWeight: 700 }}>{statusLabel(progress.status)} · Details</small></summary>
    <div style={{ padding: "0 4px 16px 35px", display: "grid", gap: 10 }}><p className="db-helper">{String(requirement.plain_language_description || requirement.what_this_is || requirement.description || "Preparation checklist")}</p>
      {sectionsFor(requirement).map((section) => <details key={section.title} className="db-list-card" style={{ padding: 0 }}><summary style={{ cursor: "pointer", fontWeight: 750, padding: "10px 12px" }}>{section.title}</summary><div style={{ borderTop: "1px solid #EEE6DF" }}>{section.items.map((entry) => { const value = saved[entry.key] || "Not Yet"; const key = `${requirement.id}:${entry.key}`; return <div key={entry.key} style={{ padding: "9px 12px", display: "grid", gridTemplateColumns: "minmax(180px,1fr) minmax(120px,160px)", gap: 10, alignItems: "center", borderBottom: "1px solid #F1EAE4" }}><div><strong style={{ fontSize: 13 }}>{entry.label}</strong>{entry.note ? <p className="db-helper" style={{ margin: "3px 0 0" }}>{entry.note}</p> : null}</div><select className="db-input" value={value} aria-label={`${entry.label} status`} disabled={savingItem === key} onChange={(event) => void saveChecklistItem(String(requirement.id), entry.key, event.target.value as ChecklistStatus)}>{checklistStatuses.map((status) => <option key={status}>{status}</option>)}</select></div>; })}</div></details>)}
      <p className="db-helper"><strong>Next action:</strong> {nextRequirementAction(progress.status, state?.verification_status === "Verified", String(requirement.next_action_guidance || requirement.school_action || "") || null)}</p><p className="db-helper"><strong>Evidence:</strong> {evidence.length ? `${evidence.length} linked` : "No evidence linked yet"}</p>
      <details><summary style={{ cursor: "pointer", fontWeight: 700 }}>Evidence, notes and dates</summary><div style={{ display: "grid", gap: 8, marginTop: 8 }}>{state ? <label>Link existing evidence<select className="db-input" defaultValue="" onChange={(event) => { if (event.target.value) void linkEvidence(String(state.id), event.target.value); }}><option value="">Choose document</option>{documents.map((document) => <option key={String(document.id)} value={String(document.id)}>{String(document.document_name)}</option>)}</select></label> : <p className="db-helper">Record one checklist item before linking evidence.</p>}<Link className="db-button-secondary" href={`/dbe-registration/documents?school=${school}`}>Upload document</Link><form onSubmit={(event) => { event.preventDefault(); void saveDetails(requirement, event.currentTarget); }} style={{ display: "grid", gap: 8 }}><label>Expiry date<input className="db-input" name="expires_at" type="date" defaultValue={String(state?.expires_at || "")} /></label><label>Notes<textarea className="db-input" name="notes" defaultValue={String(state?.notes || "")} /></label><label><input type="checkbox" name="verify" defaultChecked={state?.verification_status === "Verified"} /> Mark recorded information as reviewed</label><button className="db-button-primary">Save details</button></form>{state?.expires_at ? <p className="db-helper">Recorded expiry: {formatComplianceDate(String(state.expires_at))}</p> : null}</div></details>
      <details><summary style={{ cursor: "pointer", fontWeight: 700 }}>Source &amp; guidance</summary><p className="db-helper"><strong>Source:</strong> {source.source}<br /><strong>Applies to:</strong> {source.applies}<br />{source.detail}</p>{requirement.source_url ? <a className="db-button-secondary" href={String(requirement.source_url)} target="_blank" rel="noreferrer">Open source</a> : null}<p className="db-helper"><strong>Ready means:</strong> {String(requirement.ready_definition || READY_EXPLANATION)}</p></details>
    </div></details>;
}
