"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { ACTION_PRIORITIES, ACTION_STATUSES, normalizeCorrectiveActionPriority } from "@/app/lib/corrective-actions";
import { authenticatedFetch } from "@/app/lib/authenticated-fetch";
import { getCurrentProfile } from "@/app/lib/auth";
import { resolveSchoolContext } from "@/app/lib/school-context";
import { ComplianceHeader, formatComplianceDate } from "../components";

type Action = Record<string, unknown> & { id: string; title: string; status: string; priority: string; due_date: string | null; evidence: Record<string, unknown>[]; overdue: boolean; due_soon: boolean };
type Staff = { id: string; name: string; role: string; active: boolean };
type Payload = { items: Action[]; summary: { open: number; inProgress: number; readyForVerification: number; closed: number; overdue: number; dueSoon: number }; staff: Staff[]; documents: Record<string, unknown>[] };
const statusFilters = ["All Active", ...ACTION_STATUSES];
const sourceLabels: Record<string, string> = { inspection_finding: "Inspection Finding", requirement: "Requirement", manual: "Manual" };
const sourceRoutes: Record<string, string> = { inspection_finding: "/dbe-registration/inspections", requirement: "/dbe-registration/requirements" };

export default function CorrectiveActionsPage() {
  const router = useRouter(); const params = useSearchParams(); const [schoolId, setSchoolId] = useState<number>(); const [data, setData] = useState<Payload>(); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [selected, setSelected] = useState<Action>();
  const [status, setStatus] = useState("All Active"); const [priority, setPriority] = useState("All"); const [source, setSource] = useState("All"); const [responsible, setResponsible] = useState("All"); const [attention, setAttention] = useState("All"); const [search, setSearch] = useState(""); const [showCreate, setShowCreate] = useState(Boolean(params.get("source_type")));
  const load = async (id: number) => { const response = await authenticatedFetch(`/api/compliance/corrective-actions?school_id=${id}`); const body = await response.json(); if (!response.ok) throw new Error(body.error || "Corrective actions could not be loaded."); setData(body); };
  useEffect(() => { void (async () => { try { const { profile } = await getCurrentProfile(); if (!profile || profile.role === "teacher") { router.replace(profile ? "/teacher" : "/login"); return; } const context = await resolveSchoolContext(params.get("school")); if (!context.schoolId) { router.replace("/login"); return; } setSchoolId(context.schoolId); await load(context.schoolId); } catch (error) { alert(error instanceof Error ? error.message : "Corrective actions could not be loaded."); } finally { setLoading(false); } })(); }, [params, router]);
  const items = useMemo(() => (data?.items || []).filter((item) => {
    const text = `${item.title} ${item.description || ""} ${item.responsible_name || ""}`.toLowerCase();
    const attentionMatches = attention === "All" || (attention === "Overdue" ? item.overdue : item.due_soon);
    return (status === "All Active" ? item.status !== "Closed" : status === "All" || item.status === status) && (priority === "All" || item.priority === priority) && (source === "All" || item.source_type === source) && (responsible === "All" || item.responsible_user_id === responsible) && attentionMatches && (!search || text.includes(search.toLowerCase()));
  }), [attention, data?.items, priority, responsible, search, source, status]);
  const request = async (payload: Record<string, unknown>) => { if (!schoolId) return; setSaving(true); try { const response = await authenticatedFetch("/api/compliance/corrective-actions", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ school_id: schoolId, ...payload }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error || "The corrective action could not be saved."); await load(schoolId); setSelected(undefined); return body; } catch (error) { alert(error instanceof Error ? error.message : "The corrective action could not be saved."); } finally { setSaving(false); } };
  const create = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const result = await request({ action: "create", title: form.get("title"), description: form.get("description"), priority: form.get("priority"), responsible_user_id: form.get("responsible_user_id"), due_date: form.get("due_date"), source_type: params.get("source_type") || "manual", source_id: params.get("source_id") || "" }); if (result) { event.currentTarget.reset(); setShowCreate(false); router.replace(`/dbe-registration/corrective-actions${params.get("school") ? `?school=${params.get("school")}` : ""}`); } };
  if (loading) return <p>Loading corrective actions...</p>;
  const summary = data?.summary || { open: 0, inProgress: 0, readyForVerification: 0, overdue: 0, closed: 0, dueSoon: 0 };
  const schoolQuery = params.get("school") ? `?school=${params.get("school")}` : ""; const sourceType = params.get("source_type") || "manual";
  return <div><ComplianceHeader title="Corrective Actions" description="Track remediation from the issue through evidence, verification and closure. Closing an action does not change its source record." />
    <section style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(145px,1fr))", gap: 10, marginBottom: 14 }}>{[["Open", summary.open], ["In Progress", summary.inProgress], ["Ready for Verification", summary.readyForVerification], ["Overdue", summary.overdue], ["Closed", summary.closed]].map(([label, value]) => <div className="db-card" style={{ padding: 14 }} key={String(label)}><strong>{String(label)}</strong><div style={{ fontSize: 28, marginTop: 4 }}>{String(value)}</div></div>)}</section>
    <section className="db-card db-card-blue" style={{ padding: 16, marginBottom: 14 }}><div style={{ display: "flex", justifyContent: "space-between", gap: 10, flexWrap: "wrap" }}><div><h3 style={{ margin: 0 }}>{sourceType === "manual" ? "Create a manual corrective action" : `Create from ${sourceLabels[sourceType] || "source"}`}</h3><p className="db-helper">Assign an active school staff member and set a due date. Source records remain authoritative.</p></div><button className="db-button-secondary" onClick={() => setShowCreate((value) => !value)}>{showCreate ? "Close" : "Create action"}</button></div>
      {showCreate ? <form onSubmit={(event) => void create(event)} style={{ display: "grid", gap: 9, marginTop: 12 }}><label>Title<input className="db-input" required name="title" defaultValue={sourceType === "inspection_finding" ? "Resolve inspection finding" : sourceType === "requirement" ? "Resolve compliance requirement" : ""} /></label><label>Description<textarea className="db-input" required name="description" defaultValue={sourceType === "inspection_finding" ? "Resolve the recorded inspection finding and submit evidence for verification." : sourceType === "requirement" ? "Review and resolve the recorded compliance requirement status." : ""} /></label><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(180px,1fr))", gap: 9 }}><label>Priority<select className="db-input" name="priority" defaultValue="Medium">{ACTION_PRIORITIES.map((item) => <option key={item}>{item}</option>)}</select></label><label>Responsible person<select className="db-input" name="responsible_user_id" required defaultValue=""><option value="">Choose active staff member</option>{(data?.staff || []).filter((item) => item.active).map((item) => <option key={item.id} value={item.id}>{item.name} · {item.role}</option>)}</select></label><label>Due date<input className="db-input" required type="date" name="due_date" /></label></div><button className="db-button-primary" disabled={saving}>{saving ? "Saving..." : "Create corrective action"}</button></form> : null}</section>
    <section className="db-card" style={{ padding: 16 }}><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(160px,1fr))", gap: 8 }}><input className="db-input" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search action or responsible person" /><select className="db-input" value={status} onChange={(event) => setStatus(event.target.value)}>{statusFilters.map((item) => <option key={item}>{item}</option>)}</select><select className="db-input" value={attention} onChange={(event) => setAttention(event.target.value)}><option>All</option><option>Overdue</option><option>Due Soon</option></select><select className="db-input" value={priority} onChange={(event) => setPriority(event.target.value)}><option>All</option>{ACTION_PRIORITIES.map((item) => <option key={item}>{item}</option>)}</select><select className="db-input" value={source} onChange={(event) => setSource(event.target.value)}><option>All</option>{Object.entries(sourceLabels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select><select className="db-input" value={responsible} onChange={(event) => setResponsible(event.target.value)}><option>All</option>{(data?.staff || []).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div><h3 style={{ marginTop: 16 }}>Corrective actions ({items.length})</h3>{items.length ? <div style={{ display: "grid", gap: 10 }}>{items.map((item) => <ActionCard key={item.id} action={item} schoolQuery={schoolQuery} open={() => setSelected(item)} />)}</div> : <p className="db-helper">No corrective actions currently require attention.</p>}</section>
    {selected ? <ActionDetail action={selected} documents={data?.documents || []} schoolQuery={schoolQuery} saving={saving} request={request} close={() => setSelected(undefined)} /> : null}
  </div>;
}

function ActionCard({ action, schoolQuery, open }: { action: Action; schoolQuery: string; open: () => void }) { return <article className="db-list-card"><div style={{ display: "flex", justifyContent: "space-between", gap: 10, flexWrap: "wrap" }}><div><strong>{action.title}</strong><p className="db-helper">{String(action.source_label)} · {String(action.responsible_name)}{action.responsible_role ? ` · ${String(action.responsible_role)}` : ""}</p></div><div><strong>{normalizeCorrectiveActionPriority(action.priority)}</strong><p className="db-helper">{String(action.status)}{action.overdue ? " · Overdue" : action.due_soon ? " · Due soon" : ""}</p></div></div><p className="db-helper">Due: {formatComplianceDate(action.due_date, "Not set")}</p><button className="db-button-secondary" onClick={open}>Open action</button>{sourceRoutes[String(action.source_type)] ? <Link className="db-button-secondary" style={{ marginLeft: 8, textDecoration: "none" }} href={`${sourceRoutes[String(action.source_type)]}${schoolQuery}`}>View source</Link> : null}</article>; }

function ActionDetail({ action, documents, schoolQuery, saving, request, close }: { action: Action; documents: Record<string, unknown>[]; schoolQuery: string; saving: boolean; request: (body: Record<string, unknown>) => Promise<unknown>; close: () => void }) {
  const [note, setNote] = useState(""); const transitions: Record<string, [string, string][]> = { Open: [["In Progress", "Start work"]], "In Progress": [["Ready for Verification", "Submit for verification"]], "Ready for Verification": [["Closed", "Verify and close"], ["In Progress", "Return for correction"]], Closed: [["Reopened", "Reopen"]], Reopened: [["In Progress", "Resume work"]] };
  const run = async (next: string) => { const result = await request({ action: "transition", id: action.id, status: next, note }); if (result) { setNote(""); close(); } };
  return <section className="db-card db-card-lavender" style={{ padding: 18, marginTop: 14 }}><button className="db-button-secondary" onClick={close}>Close detail</button><h2>{action.title}</h2><p>{String(action.description || "No description recorded.")}</p><p className="db-helper">{String(action.source_context)} · Due {formatComplianceDate(action.due_date, "not set")} · {String(action.status)}{action.overdue ? " · Overdue" : action.due_soon ? " · Due soon" : ""}</p><p className="db-helper">Responsible: {String(action.responsible_name)}{action.responsible_active === false && action.responsible_user_id ? " (historical assignment)" : ""}</p>{sourceRoutes[String(action.source_type)] ? <Link className="db-button-secondary" style={{ textDecoration: "none" }} href={`${sourceRoutes[String(action.source_type)]}${schoolQuery}`}>View source</Link> : null}
    <div style={{ marginTop: 14 }}><h3>Evidence</h3>{action.evidence.length ? action.evidence.map((item) => <div className="db-list-card" key={String(item.id)}>{String(item.document_name)} <button className="db-button-secondary" disabled={saving} onClick={() => void request({ action: "unlink_evidence", id: action.id, document_id: item.document_id })}>Unlink</button></div>) : <p className="db-helper">No evidence linked yet.</p>}<label>Link an existing private compliance document<select className="db-input" defaultValue="" onChange={(event) => { if (event.target.value) void request({ action: "link_evidence", id: action.id, document_id: event.target.value }); }}><option value="">Choose document</option>{documents.map((item) => <option key={String(item.id)} value={String(item.id)}>{String(item.document_name)}</option>)}</select></label></div>
    <div style={{ marginTop: 14 }}><h3>Workflow</h3><label>Resolution, verification or reopening note<textarea className="db-input" value={note} onChange={(event) => setNote(event.target.value)} placeholder="Required when submitting, verifying, returning or reopening." /></label><div style={{ display: "flex", gap: 8, flexWrap: "wrap", marginTop: 8 }}>{(transitions[String(action.status)] || []).map(([next, label]) => <button className="db-button-primary" key={next} disabled={saving} onClick={() => void run(next)}>{label}</button>)}</div></div>
    <div style={{ marginTop: 14 }}><h3>Timeline</h3><p className="db-helper">Created: {formatComplianceDate(String(action.created_at || ""), "Not recorded")} · Started: {formatComplianceDate(String(action.started_at || ""), "Not started")} · Submitted: {formatComplianceDate(String(action.submitted_for_verification_at || ""), "Not submitted")} · Verified: {formatComplianceDate(String(action.verified_at || ""), "Not verified")} · Closed: {formatComplianceDate(String(action.closed_at || ""), "Not closed")} · Reopened: {formatComplianceDate(String(action.reopened_at || ""), "Not reopened")}</p></div>
  </section>;
}
