"use client";

import { FormEvent, useEffect, useState } from "react";
import { useParams, useRouter, useSearchParams } from "next/navigation";
import { authenticatedFetch } from "@/app/lib/authenticated-fetch";
import { getCurrentProfile } from "@/app/lib/auth";
import { resolveSchoolContext } from "@/app/lib/school-context";
import { classifyExpiry, correctiveActionState } from "@/app/lib/compliance";
import { ComplianceHeader } from "../components";

const config: Record<string, { title: string; description: string; resource: "requirements" | "staff" | "inspections" | "actions" | "certificates"; empty: string }> = {
  requirements: { title: "Requirements", description: "Track school-specific readiness separately from evidence and official status.", resource: "requirements", empty: "No requirements have been started yet." },
  "staff-compliance": { title: "Staff Compliance", description: "Individual staff compliance register. Only record items that apply to the person.", resource: "staff", empty: "No staff compliance items have been recorded yet." },
  "health-safety": { title: "Health & Safety", description: "Use shared requirements for health and safety evidence, verification and follow-up.", resource: "requirements", empty: "No health and safety requirements have been started yet." },
  premises: { title: "Premises", description: "Track premises and site evidence without making unsupported regulatory claims.", resource: "requirements", empty: "No premises requirements have been started yet." },
  inspections: { title: "Inspections", description: "Record internal or external inspections. An entry is not an official government record unless supported by official evidence.", resource: "inspections", empty: "No inspections have been recorded yet." },
  "corrective-actions": { title: "Corrective Actions", description: "Follow issues through from Open to In Progress, Ready for Verification and Closed.", resource: "actions", empty: "No corrective actions are currently open." },
  certificates: { title: "Certificates & Renewals", description: "A central register of dates that need renewal or attention.", resource: "certificates", empty: "No certificates are expiring in the next 30 days." },
};

export default function ComplianceSectionPage() {
  const { section } = useParams<{ section: string }>(); const page = config[section]; const router = useRouter(); const params = useSearchParams();
  const [schoolId, setSchoolId] = useState<number>(); const [items, setItems] = useState<Array<Record<string, unknown>>>([]); const [catalogue, setCatalogue] = useState<Array<Record<string, unknown>>>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [form, setForm] = useState<Record<string, string>>({ status: "Not Started", priority: "Normal", inspection_scope: "Internal", renewal_status: "Current" });
  const load = async (id: number) => { const [result, catalog] = await Promise.all([authenticatedFetch(`/api/compliance?school_id=${id}&resource=${page.resource}`).then((r) => r.json()), authenticatedFetch(`/api/compliance?school_id=${id}&resource=catalogue`).then((r) => r.json())]); setItems(result.items || []); setCatalogue(catalog.items || []); };
  // `load` is intentionally invoked for the resolved school only; including it
  // here would re-run the bootstrap after each list state update.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { void (async () => { if (!page) { router.replace("/dbe-registration/overview"); return; } const { profile } = await getCurrentProfile(); if (!profile || profile.role === "teacher") { router.replace(profile ? "/teacher" : "/login"); return; } const context = await resolveSchoolContext(params.get("school")); if (!context.schoolId) { router.replace(context.shouldReturnToMaster ? "/master" : "/login"); return; } setSchoolId(context.schoolId); await load(context.schoolId); setLoading(false); })(); }, [page, params, router]);
  if (!page || loading) return <p>Loading compliance information...</p>;
  const set = (name: string, value: string) => setForm((current) => ({ ...current, [name]: value }));
  const save = async (event: FormEvent) => { event.preventDefault(); if (!schoolId) return; setSaving(true); const response = await authenticatedFetch("/api/compliance", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ school_id: schoolId, resource: page.resource, ...form }) }); const result = await response.json(); if (!response.ok) alert(result.error || "Could not save the compliance item."); else { setForm({ status: "Not Started", priority: "Normal", inspection_scope: "Internal", renewal_status: "Current" }); await load(schoolId); } setSaving(false); };
  const updateStatus = async (item: Record<string, unknown>, status: string) => { if (!schoolId) return; const response = await authenticatedFetch("/api/compliance", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ school_id: schoolId, resource: page.resource, id: item.id, status }) }); if (!response.ok) { const result = await response.json(); alert(result.error || "Could not update this item."); return; } await load(schoolId); };
  const requirementCatalogue = catalogue.filter((item) => section === "health-safety" ? item.requirement_group === "Health & Safety" : section === "premises" ? item.applies_to_premises : true);
  return <div><ComplianceHeader title={page.title} description={page.description} />
    <div className="db-card db-card-blue" style={{ padding: 16, marginBottom: 16 }}><h3 style={{ marginTop: 0 }}>Add item</h3><form onSubmit={save} style={{ display: "grid", gap: 10 }}>
      {page.resource === "requirements" ? <><label>Requirement<select className="db-input" required value={form.requirement_id || ""} onChange={(e) => set("requirement_id", e.target.value)}><option value="">Choose a configured requirement</option>{requirementCatalogue.map((item) => <option key={String(item.id)} value={String(item.id)}>{String(item.title)}</option>)}</select></label><label>Status<select className="db-input" value={form.status} onChange={(e) => set("status", e.target.value)}>{["Not Started", "In Progress", "Ready", "Needs Review", "Missing", "Expired", "Not Applicable"].map((value) => <option key={value}>{value}</option>)}</select></label></> : null}
      {page.resource === "staff" ? <><label>Staff user ID<input className="db-input" required value={form.staff_user_id || ""} onChange={(e) => set("staff_user_id", e.target.value)} placeholder="Select from staff directory (ID)" /></label><label>Compliance item<input className="db-input" required value={form.title || ""} onChange={(e) => set("title", e.target.value)} placeholder="Example: First-aid certification" /></label><label>Expiry date<input className="db-input" type="date" value={form.expiry_date || ""} onChange={(e) => set("expiry_date", e.target.value)} /></label></> : null}
      {page.resource === "inspections" ? <><><label>Inspection type<input className="db-input" required value={form.inspection_type || ""} onChange={(e) => set("inspection_type", e.target.value)} /></label><label>Scope<select className="db-input" value={form.inspection_scope} onChange={(e) => set("inspection_scope", e.target.value)}><option>Internal</option><option>External / Official</option></select></label><label>Scheduled date<input className="db-input" type="date" value={form.scheduled_date || ""} onChange={(e) => set("scheduled_date", e.target.value)} /></label></></> : null}
      {page.resource === "actions" ? <><label>Corrective action<input className="db-input" required value={form.title || ""} onChange={(e) => set("title", e.target.value)} /></label><label>Due date<input className="db-input" type="date" value={form.due_date || ""} onChange={(e) => set("due_date", e.target.value)} /></label></> : null}
      {page.resource === "certificates" ? <><label>Certificate / renewal type<input className="db-input" required value={form.certificate_type || ""} onChange={(e) => set("certificate_type", e.target.value)} /></label><label>Expiry date<input className="db-input" type="date" value={form.expiry_date || ""} onChange={(e) => set("expiry_date", e.target.value)} /></label></> : null}
      <label>Notes<textarea className="db-input" value={form.notes || ""} onChange={(e) => set("notes", e.target.value)} /></label><button className="db-button-primary" disabled={saving}>{saving ? "Saving..." : "Save item"}</button></form></div>
    <div className="db-card db-card-lavender" style={{ padding: 16 }}><h3 style={{ marginTop: 0 }}>Recorded items ({items.length})</h3>{items.length === 0 ? <p className="db-helper">{page.empty}</p> : <div style={{ display: "grid", gap: 10 }}>{items.map((item) => { const title = String(item.title || item.inspection_type || item.certificate_type || item.requirement_id || "Compliance item"); const state = page.resource === "actions" ? correctiveActionState(String(item.status), String(item.due_date || "") || null) : item.expiry_date ? classifyExpiry(String(item.expiry_date)) : String(item.status || item.renewal_status || "Recorded"); return <div className="db-list-card" key={String(item.id)}><strong>{title}</strong><p className="db-helper">{String(state)}</p>{page.resource === "actions" && String(item.status) !== "Closed" ? <button className="db-button-secondary" onClick={() => updateStatus(item, "Closed")}>Mark closed</button> : null}</div>; })}</div>}</div>
  </div>;
}
