import { NextResponse } from "next/server";
import { PERMISSIONS } from "@/app/lib/permissions";
import { requireStaffPermission, writeRequiredSecurityAudit } from "@/app/lib/server-authorization";
import { supabaseAdmin } from "@/app/lib/supabase-admin";

const text = (value: unknown, max = 2000) => String(value ?? "").trim().slice(0, max) || null;
const fields = ["title", "plain_language_title", "description", "requirement_category", "requirement_status", "authority_type", "authority_name", "source_title", "source_reference", "source_url", "source_version", "source_effective_date", "source_last_verified_at", "applicability_scope", "country", "province", "municipality", "programme_type", "registration_stage", "evidence_required", "minimum_evidence_count", "expires", "renewal_frequency_months", "guidance_notes", "active"] as const;
async function access(request: Request) { return requireStaffPermission(request, PERMISSIONS.PLATFORM_REPORTS_VIEW); }
export async function GET(request: Request) { const authorization = await access(request); if (!authorization.ok || !authorization.staff.isPlatformUser) return authorization.ok ? NextResponse.json({ error: "Master access required." }, { status: 403 }) : authorization.response; const { data, error } = await supabaseAdmin.from("compliance_requirements").select("*").order("active", { ascending: false }).order("display_order"); return error ? NextResponse.json({ error: error.message }, { status: 400 }) : NextResponse.json({ items: data || [] }); }
export async function PATCH(request: Request) { const authorization = await access(request); if (!authorization.ok || !authorization.staff.isPlatformUser) return authorization.ok ? NextResponse.json({ error: "Master access required." }, { status: 403 }) : authorization.response; const body = await request.json(); const id = text(body.id, 64); if (!id) return NextResponse.json({ error: "Requirement required." }, { status: 400 }); const updates: Record<string, unknown> = { updated_at: new Date().toISOString(), updated_by: authorization.staff.userId }; for (const field of fields) if (body[field] !== undefined) updates[field] = typeof body[field] === "boolean" || typeof body[field] === "number" ? body[field] : text(body[field]); const { error } = await supabaseAdmin.from("compliance_requirements").update(updates).eq("id", id); if (error) return NextResponse.json({ error: error.message }, { status: 400 }); await writeRequiredSecurityAudit(authorization.staff, "compliance.catalogue_requirement_updated", { fields: Object.keys(updates).filter((key) => !["updated_at", "updated_by"].includes(key)) }, { type: "compliance_requirements", id }); return NextResponse.json({ success: true }); }
