-- Durable payment-receipt delivery and auditable payment adjustments.
-- Payment rows remain the source of truth. A reversal/refund reduces the
-- effective payment amount while preserving its original value and history.

alter table public.subscription_payments
  add column if not exists original_amount numeric(12,2);

update public.subscription_payments
set original_amount = amount
where original_amount is null;

alter table public.subscription_payments
  alter column original_amount set not null;

create or replace function public.set_billing_payment_original_amount()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.original_amount := coalesce(new.original_amount, new.amount);
  return new;
end;
$$;

drop trigger if exists set_billing_payment_original_amount_trigger
  on public.subscription_payments;
create trigger set_billing_payment_original_amount_trigger
before insert on public.subscription_payments
for each row execute function public.set_billing_payment_original_amount();

create table if not exists public.billing_payment_adjustments (
  id bigint generated by default as identity primary key,
  school_id bigint not null references public.schools(id) on delete restrict,
  payment_id bigint not null references public.subscription_payments(id) on delete restrict,
  adjustment_type text not null check (adjustment_type in ('reversal', 'refund')),
  amount numeric(12,2) not null check (amount > 0),
  reason text not null check (char_length(trim(reason)) >= 3),
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists billing_payment_adjustments_school_date_idx
  on public.billing_payment_adjustments (school_id, created_at desc);
create index if not exists billing_payment_adjustments_payment_idx
  on public.billing_payment_adjustments (payment_id, created_at desc);

alter table public.billing_payment_adjustments enable row level security;
grant select on public.billing_payment_adjustments to authenticated;

drop policy if exists "Billing adjustment authorised read"
  on public.billing_payment_adjustments;
create policy "Billing adjustment authorised read"
on public.billing_payment_adjustments for select to authenticated
using (
  public.current_platform_has_permission('billing.manage')
  or exists (
    select 1
    from public.profiles profile
    where profile.id = auth.uid()
      and profile.school_id = billing_payment_adjustments.school_id
      and profile.is_active is distinct from false
      and profile.role in ('owner', 'principal')
  )
  or exists (
    select 1
    from public.school_memberships membership
    where membership.user_id = auth.uid()
      and membership.school_id = billing_payment_adjustments.school_id
      and membership.status = 'active'
      and (
        membership.role in ('owner', 'principal')
        or 'billing.manage' = any(coalesce(membership.permissions, '{}'::text[]))
      )
  )
);

create table if not exists public.billing_email_outbox (
  id uuid primary key default gen_random_uuid(),
  school_id bigint not null references public.schools(id) on delete restrict,
  payment_id bigint not null references public.subscription_payments(id) on delete restrict,
  email_type text not null default 'payment_receipt'
    check (email_type = 'payment_receipt'),
  status text not null default 'pending'
    check (status in ('pending', 'processing', 'sent', 'failed')),
  attempts integer not null default 0 check (attempts >= 0),
  next_attempt_at timestamptz not null default now(),
  last_error text,
  sent_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (payment_id, email_type)
);

create index if not exists billing_email_outbox_retry_idx
  on public.billing_email_outbox (status, next_attempt_at, created_at)
  where status in ('pending', 'failed');

alter table public.billing_email_outbox enable row level security;
revoke all on public.billing_email_outbox from public, anon, authenticated;
grant all on public.billing_email_outbox to service_role;

create or replace function public.queue_billing_payment_receipt()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.billing_email_outbox (
    school_id,
    payment_id,
    email_type,
    status,
    next_attempt_at
  )
  values (
    new.school_id,
    new.id,
    'payment_receipt',
    'pending',
    now()
  )
  on conflict (payment_id, email_type) do nothing;
  return new;
end;
$$;

drop trigger if exists queue_billing_payment_receipt_trigger
  on public.subscription_payments;
create trigger queue_billing_payment_receipt_trigger
after insert on public.subscription_payments
for each row execute function public.queue_billing_payment_receipt();

-- Queue receipts for historical payments only when no delivery record exists.
-- They remain failed/held until explicitly processed, preventing an unexpected
-- bulk email when this migration is installed.
insert into public.billing_email_outbox (
  school_id,
  payment_id,
  email_type,
  status,
  attempts,
  next_attempt_at,
  last_error
)
select
  payment.school_id,
  payment.id,
  'payment_receipt',
  'failed',
  5,
  now() + interval '100 years',
  'Historical payment imported before durable receipt delivery was enabled.'
from public.subscription_payments payment
on conflict (payment_id, email_type) do nothing;

create or replace function public.claim_billing_email_outbox(
  batch_size integer default 20,
  target_payment_id bigint default null
)
returns setof public.billing_email_outbox
language plpgsql
security definer
set search_path = public
as $$
begin
  return query
  with claimable as (
    select item.id
    from public.billing_email_outbox item
    where item.status in ('pending', 'failed')
      and item.attempts < 5
      and item.next_attempt_at <= now()
      and (target_payment_id is null or item.payment_id = target_payment_id)
    order by item.created_at asc
    for update skip locked
    limit greatest(1, least(coalesce(batch_size, 20), 100))
  )
  update public.billing_email_outbox item
  set status = 'processing',
      attempts = item.attempts + 1,
      updated_at = now()
  from claimable
  where item.id = claimable.id
  returning item.*;
end;
$$;

revoke all on function public.claim_billing_email_outbox(integer, bigint)
  from public, anon, authenticated;
grant execute on function public.claim_billing_email_outbox(integer, bigint)
  to service_role;

create or replace function public.apply_billing_payment_adjustment(
  target_payment_id bigint,
  adjustment_kind text,
  adjustment_amount numeric,
  adjustment_reason text,
  actor_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  target_payment public.subscription_payments%rowtype;
  remaining_amount numeric(12,2);
  adjustment_id bigint;
  repair_result jsonb;
begin
  if adjustment_kind not in ('reversal', 'refund') then
    raise exception 'Adjustment type must be reversal or refund.';
  end if;
  if adjustment_amount <= 0 then
    raise exception 'Adjustment amount must be greater than zero.';
  end if;
  if char_length(trim(coalesce(adjustment_reason, ''))) < 3 then
    raise exception 'A reason of at least 3 characters is required.';
  end if;

  select * into target_payment
  from public.subscription_payments
  where id = target_payment_id
  for update;

  if target_payment.id is null then
    raise exception 'Payment % was not found.', target_payment_id;
  end if;

  if adjustment_amount > target_payment.amount then
    raise exception 'The adjustment cannot exceed the remaining payment amount of R%.',
      to_char(target_payment.amount, 'FM999999990.00');
  end if;

  remaining_amount := target_payment.amount - adjustment_amount;

  insert into public.billing_payment_adjustments (
    school_id,
    payment_id,
    adjustment_type,
    amount,
    reason,
    created_by
  )
  values (
    target_payment.school_id,
    target_payment.id,
    adjustment_kind,
    adjustment_amount,
    trim(adjustment_reason),
    actor_id
  )
  returning id into adjustment_id;

  update public.subscription_payments
  set amount = remaining_amount,
      unapplied_amount = least(unapplied_amount, remaining_amount)
  where id = target_payment.id;

  repair_result := public.reconcile_school_billing_account(
    target_payment.school_id,
    599
  );

  return jsonb_build_object(
    'adjustment_id', adjustment_id,
    'payment_id', target_payment.id,
    'school_id', target_payment.school_id,
    'original_amount', target_payment.original_amount,
    'adjustment_amount', adjustment_amount,
    'remaining_payment_amount', remaining_amount,
    'repair', repair_result
  );
end;
$$;

revoke all on function public.apply_billing_payment_adjustment(
  bigint, text, numeric, text, uuid
) from public, anon, authenticated;
grant execute on function public.apply_billing_payment_adjustment(
  bigint, text, numeric, text, uuid
) to service_role;

comment on table public.billing_email_outbox is
  'Durable, retryable delivery queue for the single receipt email sent after a payment is recorded.';
comment on table public.billing_payment_adjustments is
  'Immutable audit history for payment reversals and refunds. Payments are never deleted.';
