begin;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'classroom-homework',
  'classroom-homework',
  false,
  15728640,
  array[
    'application/pdf',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'image/jpeg',
    'image/png'
  ]
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create table if not exists public.homework_library (
  id bigint generated by default as identity primary key,
  school_id bigint not null references public.schools(id) on delete cascade,
  title text not null check (char_length(title) between 1 and 160),
  notes text,
  file_name text not null,
  file_path text not null unique,
  uploaded_by uuid references auth.users(id) on delete set null,
  archived boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.homework_assignments (
  id bigint generated by default as identity primary key,
  school_id bigint not null references public.schools(id) on delete cascade,
  classroom_id bigint not null references public.classrooms(id) on delete cascade,
  week_start date not null,
  homework_id bigint references public.homework_library(id) on delete set null,
  instruction_note text,
  position smallint not null default 0 check (position between 0 and 2),
  assigned_by uuid references auth.users(id) on delete set null,
  assigned_at timestamptz not null default now(),
  unique (school_id, classroom_id, week_start, position)
);

alter table public.homework_assignments
  add column if not exists instruction_note text,
  add column if not exists position smallint not null default 0;

alter table public.homework_assignments
  drop constraint if exists homework_assignments_school_id_classroom_id_week_start_key;

create unique index if not exists homework_assignments_week_position_uidx
  on public.homework_assignments (school_id, classroom_id, week_start, position);

create index if not exists homework_library_school_active_idx on public.homework_library (school_id, archived, title);
create index if not exists homework_assignments_class_week_idx on public.homework_assignments (classroom_id, week_start desc);

alter table public.homework_library enable row level security;
alter table public.homework_assignments enable row level security;

create or replace function public.replace_classroom_homework(
  p_school_id bigint,
  p_classroom_id bigint,
  p_week_start date,
  p_assigned_by uuid,
  p_items jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not exists (
    select 1
    from public.classrooms classroom
    where classroom.id = p_classroom_id
      and classroom.school_id = p_school_id
  ) then
    raise exception 'Classroom does not belong to this school.';
  end if;

  delete from public.homework_assignments
  where school_id = p_school_id
    and classroom_id = p_classroom_id
    and week_start = p_week_start;

  insert into public.homework_assignments (
    school_id, classroom_id, week_start, homework_id,
    instruction_note, position, assigned_by
  )
  select
    p_school_id,
    p_classroom_id,
    p_week_start,
    (item->>'homework_id')::bigint,
    nullif(left(trim(item->>'instruction_note'), 500), ''),
    (item->>'position')::smallint,
    p_assigned_by
  from jsonb_array_elements(coalesce(p_items, '[]'::jsonb)) item
  where (item->>'homework_id') ~ '^[0-9]+$'
    and exists (
      select 1 from public.homework_library library
      where library.id = (item->>'homework_id')::bigint
        and library.school_id = p_school_id
        and library.archived = false
    );
end;
$$;

revoke all on function public.replace_classroom_homework(bigint, bigint, date, uuid, jsonb) from public, anon, authenticated;
grant execute on function public.replace_classroom_homework(bigint, bigint, date, uuid, jsonb) to service_role;

commit;
