-- Recurring learner services sit alongside, rather than replace, the base monthly fee.
alter table public.school_fee_types drop constraint if exists school_fee_types_fee_category_check;
alter table public.school_fee_types add constraint school_fee_types_fee_category_check
  check (fee_category in ('registration', 'monthly', 'other', 'recurring_addon'));

create table if not exists public.learner_recurring_fee_assignments (
  id bigint generated by default as identity primary key,
  school_id bigint not null references public.schools(id) on delete cascade,
  learner_id uuid not null references public.learners(id) on delete cascade,
  fee_type_id bigint not null references public.school_fee_types(id) on delete restrict,
  assigned_amount numeric(12,2) not null check (assigned_amount >= 0),
  start_date date not null default (date_trunc('month', current_date) + interval '1 month')::date,
  end_date date,
  is_active boolean not null default true,
  assigned_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (end_date is null or end_date >= start_date),
  unique (school_id, learner_id, fee_type_id)
);

create index if not exists learner_recurring_fee_assignments_active_idx
  on public.learner_recurring_fee_assignments(school_id, learner_id, is_active, start_date, end_date);
alter table public.learner_recurring_fee_assignments enable row level security;

create or replace function public.generate_learner_monthly_fee_charges(target_date date default current_date)
returns integer language plpgsql security definer set search_path = public as $$
declare month_start date := date_trunc('month', target_date)::date; inserted_count integer := 0; addon_count integer := 0;
begin
  update public.learner_fee_charges set is_scheduled = false
  where billing_period = month_start and is_scheduled = true and charge_type like 'monthly_fee%';
  insert into public.learner_fee_charges (school_id, learner_id, charge_type, description, billing_period, due_date, amount, is_scheduled)
  select learner.school_id, learner.id, 'monthly_fee', 'School fees - ' || to_char(month_start, 'FMMonth YYYY'), month_start, month_start, learner.monthly_fee, false
  from public.learners learner where coalesce(learner.is_deleted, false) = false and learner.monthly_fee > 0 and learner.fee_billing_start_date <= month_start
  on conflict (school_id, learner_id, charge_type, billing_period) do nothing;
  get diagnostics inserted_count = row_count;
  insert into public.learner_fee_charges (school_id, learner_id, charge_type, description, billing_period, due_date, amount, is_scheduled)
  select assignment.school_id, assignment.learner_id, 'recurring_addon_' || assignment.fee_type_id,
    fee.fee_name || ' - ' || to_char(month_start, 'FMMonth YYYY'), month_start, month_start, assignment.assigned_amount, false
  from public.learner_recurring_fee_assignments assignment
  join public.school_fee_types fee on fee.id = assignment.fee_type_id and fee.school_id = assignment.school_id
  join public.learners learner on learner.id = assignment.learner_id and learner.school_id = assignment.school_id
  where assignment.is_active and fee.fee_category = 'recurring_addon' and coalesce(learner.is_deleted, false) = false
    and assignment.start_date <= month_start and (assignment.end_date is null or assignment.end_date >= month_start)
  on conflict (school_id, learner_id, charge_type, billing_period) do nothing;
  get diagnostics addon_count = row_count;
  return inserted_count + addon_count;
end;
$$;

revoke all on function public.generate_learner_monthly_fee_charges(date) from public;
grant execute on function public.generate_learner_monthly_fee_charges(date) to service_role;
