create table if not exists public.learner_support_updates (
  id bigint generated by default as identity primary key,
  school_id bigint not null references public.schools(id) on delete cascade,
  classroom_id bigint not null references public.classrooms(id) on delete cascade,
  learner_id uuid not null references public.learners(id) on delete cascade,
  outcome_id bigint not null references public.learner_activity_outcomes(id) on delete cascade,
  support_status text not null
    check (support_status in ('new', 'active', 'improving', 'monitoring', 'resolved')),
  intervention text,
  progress_note text,
  parent_summary text,
  next_review_date date,
  recorded_by uuid references auth.users(id) on delete set null,
  recorded_by_name text,
  recorded_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  constraint learner_support_update_has_detail
    check (
      nullif(btrim(coalesce(intervention, '')), '') is not null
      or nullif(btrim(coalesce(progress_note, '')), '') is not null
      or nullif(btrim(coalesce(parent_summary, '')), '') is not null
    )
);

create index if not exists learner_support_updates_school_learner_date_idx
  on public.learner_support_updates (school_id, learner_id, recorded_at desc);

create index if not exists learner_support_updates_outcome_date_idx
  on public.learner_support_updates (outcome_id, recorded_at desc);

alter table public.learner_support_updates enable row level security;

comment on table public.learner_support_updates is
  'Append-only intervention and progress history for classroom learner support cases. Access is mediated by the authorized server API.';

create or replace function public.complete_classroom_activity(
  p_school_id bigint,
  p_plan_id bigint,
  p_recorded_by uuid,
  p_support_rows jsonb
)
returns void
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_plan public.weekly_activity_plans%rowtype;
  v_row record;
  v_existing_id bigint;
begin
  select * into v_plan
  from public.weekly_activity_plans
  where id = p_plan_id and school_id = p_school_id
  for update;

  if not found then
    raise exception 'Activity plan not found.';
  end if;

  delete from public.learner_activity_outcomes
  where weekly_plan_id = p_plan_id and school_id = p_school_id;

  for v_row in
    select * from jsonb_to_recordset(p_support_rows) as x(
      learner_id uuid,
      support_status text,
      observation text
    )
  loop
    select id into v_existing_id
    from public.learner_activity_outcomes
    where school_id = p_school_id
      and learner_id = v_row.learner_id
      and developmental_area = v_plan.developmental_area
      and outcome_status = 'needs_support'
      and coalesce(support_status, 'new') <> 'resolved'
      and weekly_plan_id is distinct from p_plan_id
    order by created_at desc
    limit 1
    for update;

    if v_existing_id is not null then
      update public.learner_activity_outcomes
      set weekly_plan_id = p_plan_id,
          classroom_id = v_plan.classroom_id,
          theme = v_plan.theme,
          activity_date = v_plan.activity_date,
          activity_name = v_plan.activity_name,
          support_status = coalesce(v_row.support_status, 'new'),
          observation = nullif(v_row.observation, ''),
          recorded_by = p_recorded_by,
          updated_at = now()
      where id = v_existing_id;
    else
      insert into public.learner_activity_outcomes (
        school_id, classroom_id, learner_id, weekly_plan_id,
        developmental_area, theme, activity_date, activity_name,
        outcome_status, support_status, observation, recorded_by
      ) values (
        p_school_id, v_plan.classroom_id, v_row.learner_id, p_plan_id,
        v_plan.developmental_area, v_plan.theme, v_plan.activity_date,
        v_plan.activity_name, 'needs_support',
        coalesce(v_row.support_status, 'new'),
        nullif(v_row.observation, ''), p_recorded_by
      );
    end if;

    v_existing_id := null;
  end loop;

  update public.weekly_activity_plans
  set completed = true,
      completed_at = now(),
      completed_by = p_recorded_by
  where id = p_plan_id and school_id = p_school_id;
end;
$$;
