begin;

-- Report periods keep their term explicitly. Existing periods are backfilled
-- once from their title so current schools retain their data.
alter table public.report_periods
  add column if not exists term_number smallint;

update public.report_periods
set term_number = substring(coalesce(title, '') from '(?i)term\s*([1-4])')::smallint
where term_number is null
  and coalesce(title, '') ~* 'term\s*[1-4]';

alter table public.report_periods
  drop constraint if exists report_periods_term_number_check;
alter table public.report_periods
  add constraint report_periods_term_number_check
  check (term_number is null or term_number between 1 and 4);

-- Grade R activity metadata supports real term/week collections and carries
-- the curriculum indicator into each learner outcome.
alter table public.activity_library
  add column if not exists term_number smallint,
  add column if not exists week_number smallint,
  add column if not exists curriculum_category text,
  add column if not exists curriculum_indicator_key text;

alter table public.activity_library
  drop constraint if exists activity_library_term_number_check;
alter table public.activity_library
  add constraint activity_library_term_number_check
  check (term_number is null or term_number between 1 and 4);
alter table public.activity_library
  drop constraint if exists activity_library_week_number_check;
alter table public.activity_library
  add constraint activity_library_week_number_check
  check (week_number is null or week_number between 1 and 10);

alter table public.learner_activity_outcomes
  add column if not exists curriculum_category text,
  add column if not exists curriculum_indicator_key text;

update public.activity_library
set curriculum_category = case
      when developmental_area = 'Mathematics' then 'mathematics'
      when developmental_area in ('Language', 'Story Time', 'Music & Movement') then 'english_home_language'
      else 'life_skills'
    end,
    curriculum_indicator_key = case
      when developmental_area = 'Mathematics' then 'counts_and_recognises_numbers'
      when developmental_area in ('Language', 'Story Time', 'Music & Movement') then 'listens_and_responds'
      when developmental_area in ('Gross Motor', 'Outdoor Play') then 'gross_motor_control'
      when developmental_area in ('Creative Art', 'Fine Motor') then 'creative_expression'
      else 'personal_social_wellbeing'
    end
where theme ~* '^Grade\s*R\s*:'
  and curriculum_indicator_key is null;

-- Existing broad Grade R activities receive a stable suggested term and week.
-- Schools can edit these fields later; the allocation prevents every term card
-- from opening the same undifferentiated list.
with ranked as (
  select id,
    row_number() over (partition by school_id, developmental_area order by theme, activity_name, id) - 1 as position
  from public.activity_library
  where theme ~* '^Grade\s*R\s*:' and term_number is null
)
update public.activity_library activity
set term_number = (ranked.position % 4) + 1,
    week_number = ((ranked.position / 4) % 10) + 1
from ranked where ranked.id = activity.id;

create index if not exists activity_library_grade_r_collection_idx
  on public.activity_library (school_id, term_number, week_number, developmental_area)
  where archived = false;

-- Stable learner references replace name joins while retaining legacy names.
alter table public.attendance add column if not exists learner_id uuid references public.learners(id) on delete set null;
alter table public.summaries add column if not exists learner_id uuid references public.learners(id) on delete set null;

update public.attendance attendance
set learner_id = (
  select learner.id from public.learners learner
  where learner.school_id = attendance.school_id and learner.name = attendance.learner_name
  order by learner.id limit 1
)
where attendance.learner_id is null
  and exists (select 1 from public.learners learner where learner.school_id = attendance.school_id and learner.name = attendance.learner_name);

update public.summaries summary
set learner_id = (
  select learner.id from public.learners learner
  where learner.school_id = summary.school_id and learner.name = summary.learner_name
  order by learner.id limit 1
)
where summary.learner_id is null
  and exists (select 1 from public.learners learner where learner.school_id = summary.school_id and learner.name = summary.learner_name);

create index if not exists attendance_learner_date_idx on public.attendance (learner_id, attendance_date desc);
create index if not exists summaries_learner_created_idx on public.summaries (learner_id, created_at desc);

-- Parent homework engagement remains separate from academic outcomes.
create table if not exists public.homework_engagement (
  id bigint generated by default as identity primary key,
  school_id bigint not null references public.schools(id) on delete cascade,
  homework_assignment_id bigint not null references public.homework_assignments(id) on delete cascade,
  learner_id uuid not null references public.learners(id) on delete cascade,
  status text not null default 'assigned' check (status in ('assigned','opened','completed')),
  opened_at timestamptz,
  completed_at timestamptz,
  updated_at timestamptz not null default now(),
  unique (homework_assignment_id, learner_id)
);
create index if not exists homework_engagement_school_status_idx
  on public.homework_engagement (school_id, status, updated_at desc);
alter table public.homework_engagement enable row level security;
revoke all on public.homework_engagement from anon, authenticated;
grant all on public.homework_engagement to service_role;

-- Populate curriculum snapshots automatically for every completion path.
create or replace function public.set_activity_outcome_curriculum()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  select library.curriculum_category, library.curriculum_indicator_key
    into new.curriculum_category, new.curriculum_indicator_key
  from public.weekly_activity_plans plan
  left join public.activity_library library on library.id = plan.activity_library_id
  where plan.id = new.weekly_plan_id;
  return new;
end;
$$;
drop trigger if exists learner_activity_outcome_curriculum on public.learner_activity_outcomes;
create trigger learner_activity_outcome_curriculum
before insert or update of weekly_plan_id on public.learner_activity_outcomes
for each row execute function public.set_activity_outcome_curriculum();

update public.learner_activity_outcomes outcome
set curriculum_category = library.curriculum_category,
    curriculum_indicator_key = library.curriculum_indicator_key
from public.weekly_activity_plans plan
join public.activity_library library on library.id = plan.activity_library_id
where outcome.weekly_plan_id = plan.id
  and outcome.curriculum_indicator_key is null;

-- Grade R is continuously assessed. Remove legacy examination values and make
-- the confirmed result equal to the SBA/continuous-assessment mark.
update public.grade_r_term_results
set exam_mark = null,
    final_mark = sba_mark,
    final_code = case
      when sba_mark >= 70 then 4
      when sba_mark >= 50 then 3
      when sba_mark >= 35 then 2
      when sba_mark is not null then 1
      else null
    end,
    updated_at = now()
where exam_mark is not null or final_mark is distinct from sba_mark;

-- Keep known mismatched 2026 Book 1 sources out of practitioner and parent use.
update public.learning_resources
set catalogue_status = 'needs_review'
where grade = 'Grade R' and academic_year = 2026
  and lower(coalesce(book_number, title, '')) like '%book 1%'
  and language in ('English', 'Afrikaans')
  and catalogue_status <> 'archived';

commit;
