-- School-owned fee catalogue and optional learner fee assignments.

create table if not exists public.school_fee_types (
  id bigint generated by default as identity primary key,
  school_id bigint not null references public.schools(id) on delete cascade,
  fee_code text not null,
  fee_name text not null,
  fee_category text not null
    check (fee_category in ('registration', 'monthly', 'other')),
  billing_frequency text not null
    check (billing_frequency in ('once_off', 'monthly')),
  amount numeric(12,2) not null default 0 check (amount >= 0),
  is_active boolean not null default true,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (school_id, fee_code)
);

create table if not exists public.learner_fee_assignments (
  id bigint generated by default as identity primary key,
  school_id bigint not null references public.schools(id) on delete cascade,
  learner_id uuid not null references public.learners(id) on delete cascade,
  fee_type_id bigint not null references public.school_fee_types(id) on delete restrict,
  assigned_amount numeric(12,2) not null check (assigned_amount >= 0),
  is_active boolean not null default true,
  assigned_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (school_id, learner_id, fee_type_id)
);

create index if not exists school_fee_types_school_active_idx
  on public.school_fee_types(school_id, is_active, fee_category);
create index if not exists learner_fee_assignments_learner_idx
  on public.learner_fee_assignments(school_id, learner_id, is_active);

alter table public.school_fee_types enable row level security;
alter table public.learner_fee_assignments enable row level security;

-- Access is intentionally through authorized server routes.

create or replace function public.initialize_school_fee_catalog()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.school_fee_types (
    school_id,
    fee_code,
    fee_name,
    fee_category,
    billing_frequency,
    amount
  )
  values
    (new.id, 'registration', 'Registration Fee', 'registration', 'once_off', 0),
    (new.id, 'monthly_school_fee', 'Monthly School Fee', 'monthly', 'monthly', 0)
  on conflict (school_id, fee_code) do nothing;

  return new;
end;
$$;

drop trigger if exists initialize_school_fee_catalog_after_school_insert
  on public.schools;
create trigger initialize_school_fee_catalog_after_school_insert
after insert on public.schools
for each row execute function public.initialize_school_fee_catalog();

insert into public.school_fee_types (
  school_id,
  fee_code,
  fee_name,
  fee_category,
  billing_frequency,
  amount
)
select
  schools.id,
  defaults.fee_code,
  defaults.fee_name,
  defaults.fee_category,
  defaults.billing_frequency,
  0
from public.schools
cross join (
  values
    ('registration', 'Registration Fee', 'registration', 'once_off'),
    ('monthly_school_fee', 'Monthly School Fee', 'monthly', 'monthly')
) as defaults(fee_code, fee_name, fee_category, billing_frequency)
on conflict (school_id, fee_code) do nothing;
