create table if not exists public.school_memberships (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  school_id bigint not null references public.schools(id) on delete cascade,
  role text not null check (role in ('owner', 'principal', 'admin', 'teacher')),
  status text not null default 'active' check (status in ('invited', 'active', 'suspended', 'revoked')),
  permissions text[] not null default '{}',
  invited_by uuid references auth.users(id),
  invited_at timestamptz,
  accepted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, school_id)
);

create table if not exists public.platform_user_roles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null check (role in ('master', 'master_admin')),
  status text not null default 'active' check (status in ('invited', 'active', 'suspended', 'revoked')),
  permissions text[] not null default '{}',
  assigned_by uuid references auth.users(id),
  assigned_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.security_audit_log (
  id bigint generated by default as identity primary key,
  actor_id uuid references auth.users(id),
  actor_name text,
  actor_role text,
  school_id bigint references public.schools(id) on delete set null,
  action text not null,
  target_type text,
  target_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists school_memberships_user_status_idx on public.school_memberships(user_id, status);
create index if not exists school_memberships_school_role_idx on public.school_memberships(school_id, role, status);
create index if not exists security_audit_school_created_idx on public.security_audit_log(school_id, created_at desc);
create index if not exists security_audit_actor_created_idx on public.security_audit_log(actor_id, created_at desc);

insert into public.platform_user_roles (user_id, role, status)
select id, 'master', 'active' from public.profiles where role = 'master'
on conflict (user_id) do nothing;

insert into public.school_memberships (user_id, school_id, role, status, accepted_at)
select id, school_id,
  case when role = 'principal' then 'principal' when role = 'admin' then 'admin' else 'teacher' end,
  case when coalesce(is_active, true) then 'active' else 'suspended' end,
  now()
from public.profiles
where school_id is not null and role in ('principal', 'admin', 'teacher')
on conflict (user_id, school_id) do nothing;

alter table public.school_memberships enable row level security;
alter table public.platform_user_roles enable row level security;
alter table public.security_audit_log enable row level security;

drop policy if exists "Users view own school memberships" on public.school_memberships;
create policy "Users view own school memberships" on public.school_memberships for select to authenticated using (user_id = auth.uid());
drop policy if exists "Platform roles view own assignment" on public.platform_user_roles;
create policy "Platform roles view own assignment" on public.platform_user_roles for select to authenticated using (user_id = auth.uid());
drop policy if exists "Staff view scoped security audit" on public.security_audit_log;
create policy "Staff view scoped security audit" on public.security_audit_log for select to authenticated using (
  actor_id = auth.uid() or exists (
    select 1 from public.platform_user_roles p where p.user_id = auth.uid() and p.status = 'active' and p.role in ('master', 'master_admin')
  ) or exists (
    select 1 from public.school_memberships m where m.user_id = auth.uid() and m.school_id = security_audit_log.school_id and m.status = 'active' and m.role in ('owner', 'principal')
  )
);

comment on table public.school_memberships is 'Future-ready school-scoped roles. Owner and admin activation remains controlled by application permissions.';
comment on table public.platform_user_roles is 'Platform-wide Master and delegated Master Admin assignments.';

create table if not exists public.api_rate_limits (
  rate_key text primary key,
  window_started_at timestamptz not null default now(),
  request_count integer not null default 0
);
alter table public.api_rate_limits enable row level security;

create or replace function public.consume_api_rate_limit(p_key text, p_limit integer, p_window_seconds integer)
returns boolean language plpgsql security definer set search_path = public as $$
declare v_count integer;
begin
  insert into public.api_rate_limits(rate_key, window_started_at, request_count)
  values (p_key, now(), 1)
  on conflict (rate_key) do update set
    window_started_at = case when api_rate_limits.window_started_at < now() - make_interval(secs => p_window_seconds) then now() else api_rate_limits.window_started_at end,
    request_count = case when api_rate_limits.window_started_at < now() - make_interval(secs => p_window_seconds) then 1 else api_rate_limits.request_count + 1 end
  returning request_count into v_count;
  return v_count <= p_limit;
end;
$$;
revoke all on function public.consume_api_rate_limit(text, integer, integer) from public, anon, authenticated;
grant execute on function public.consume_api_rate_limit(text, integer, integer) to service_role;

alter table public.parent_access
  add column if not exists session_token_hash text,
  add column if not exists session_expires_at timestamptz,
  add column if not exists temporary_pin_expires_at timestamptz,
  add column if not exists invite_sent_at timestamptz,
  add column if not exists invite_delivery_status text,
  add column if not exists invite_provider_message_id text,
  add column if not exists invite_error text,
  add column if not exists reset_otp_hash text,
  add column if not exists reset_otp_expires_at timestamptz,
  add column if not exists reset_otp_attempts integer not null default 0;
update public.parent_access set session_token = null, session_token_hash = null, session_expires_at = null where session_token is not null;
create index if not exists parent_access_session_hash_idx on public.parent_access(session_token_hash) where session_token_hash is not null;
