alter table public.incident_reports
  add column if not exists urgency text not null default 'routine',
  add column if not exists injury_occurred text not null default 'no',
  add column if not exists injured_person text,
  add column if not exists injury_description text,
  add column if not exists medical_assistance_required boolean not null default false,
  add column if not exists immediate_safety_risk boolean not null default false,
  add column if not exists behaviour_trigger text,
  add column if not exists behaviour_duration text,
  add column if not exists people_affected text,
  add column if not exists deescalation_used text,
  add column if not exists settling_support text,
  add column if not exists learner_support_required boolean not null default false,
  add column if not exists follow_up_owner text,
  add column if not exists follow_up_due_date date,
  add column if not exists resolution_notes text,
  add column if not exists resolved_at timestamptz,
  add column if not exists parent_contact_name text,
  add column if not exists parent_contact_method text,
  add column if not exists parent_contact_outcome text,
  add column if not exists parent_contact_notes text,
  add column if not exists parent_contacted_by text,
  add column if not exists parent_portal_message text,
  add column if not exists parent_portal_published_at timestamptz,
  add column if not exists parent_portal_published_by text,
  add column if not exists parent_acknowledged_at timestamptz,
  add column if not exists parent_acknowledged_by text,
  add column if not exists parent_comment text,
  add column if not exists updated_at timestamptz not null default now(),
  add column if not exists updated_by uuid;

update public.incident_reports
set status = case
  when status = 'acknowledged' then 'under_review'
  when status is null then 'submitted'
  else status
end;

alter table public.incident_reports drop constraint if exists incident_reports_status_check;
alter table public.incident_reports add constraint incident_reports_status_check
  check (status in ('submitted', 'under_review', 'follow_up_required', 'resolved'));
alter table public.incident_reports drop constraint if exists incident_reports_urgency_check;
alter table public.incident_reports add constraint incident_reports_urgency_check
  check (urgency in ('routine', 'follow_up_required', 'urgent'));
alter table public.incident_reports drop constraint if exists incident_reports_injury_occurred_check;
alter table public.incident_reports add constraint incident_reports_injury_occurred_check
  check (injury_occurred in ('no', 'learner', 'another_learner', 'staff', 'unsure'));

create index if not exists incident_reports_school_status_created_idx
  on public.incident_reports (school_id, status, created_at desc);
create index if not exists incident_reports_school_type_date_idx
  on public.incident_reports (school_id, incident_type, incident_date desc);
create index if not exists incident_reports_parent_portal_idx
  on public.incident_reports (learner_id, parent_portal_published_at desc)
  where parent_portal_published_at is not null;

create table if not exists public.incident_report_audit (
  id bigint generated by default as identity primary key,
  incident_report_id bigint not null references public.incident_reports(id) on delete cascade,
  school_id bigint not null references public.schools(id) on delete cascade,
  action text not null,
  actor_id uuid,
  actor_name text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists incident_report_audit_report_idx
  on public.incident_report_audit (incident_report_id, created_at desc);
alter table public.incident_report_audit enable row level security;

drop policy if exists "Incident audit school read" on public.incident_report_audit;
create policy "Incident audit school read" on public.incident_report_audit for select to authenticated
using (exists (
  select 1 from public.profiles
  where profiles.id = auth.uid()
    and (profiles.role = 'master' or profiles.school_id = incident_report_audit.school_id)
));
drop policy if exists "Incident audit staff insert" on public.incident_report_audit;
create policy "Incident audit staff insert" on public.incident_report_audit for insert to authenticated
with check (exists (
  select 1 from public.profiles
  where profiles.id = auth.uid()
    and profiles.role in ('teacher', 'principal', 'admin', 'master')
    and (profiles.role = 'master' or profiles.school_id = incident_report_audit.school_id)
));
-- Incident photographs contain sensitive learner information. Keep the bucket private.
update storage.buckets set public = false where id = 'incident-report-photos';
drop policy if exists "incident report photos read" on storage.objects;
drop policy if exists "incident report photos upload" on storage.objects;
create policy "Incident photos authenticated school upload" on storage.objects for insert to authenticated
with check (
  bucket_id = 'incident-report-photos'
  and exists (
    select 1 from public.profiles
    where profiles.id = auth.uid()
      and profiles.role in ('teacher', 'principal', 'admin', 'master')
      and (
        profiles.role = 'master'
        or split_part(storage.objects.name, '/', 1) = profiles.school_id::text
      )
  )
);
create policy "Incident photos authenticated school read" on storage.objects for select to authenticated
using (
  bucket_id = 'incident-report-photos'
  and exists (
    select 1 from public.profiles
    where profiles.id = auth.uid()
      and (
        profiles.role = 'master'
        or split_part(storage.objects.name, '/', 1) = profiles.school_id::text
      )
  )
);

-- Limit teachers to reports they created; school leaders retain school-wide access.
drop policy if exists "incident reports same school select" on public.incident_reports;
create policy "Incident reports role scoped read" on public.incident_reports for select to authenticated
using (exists (
  select 1 from public.profiles
  where profiles.id = auth.uid()
    and (
      profiles.role = 'master'
      or (
        profiles.school_id = incident_reports.school_id
        and (
          profiles.role in ('principal', 'admin')
          or (profiles.role = 'teacher' and incident_reports.teacher_id = auth.uid())
        )
      )
    )
));
