create table if not exists sponsor_programmes (
  id bigint generated by default as identity primary key,
  sponsor_name text not null,
  programme_name text not null,
  sponsor_type text,
  contact_person text,
  contact_email text,
  contact_phone text,
  funding_focus text,
  reporting_cycle text default 'Quarterly',
  status text default 'Active',
  created_at timestamp with time zone default now()
);

alter table schools
add column if not exists is_sponsored boolean default false;

alter table schools
add column if not exists sponsor_programme_id bigint references sponsor_programmes(id);
