begin;

-- Extend the existing Grade R resource foundation. Historical resources and
-- links are retained; no workbook record or school usage data is replaced.

alter table public.learning_resources
  add column if not exists book_number text,
  add column if not exists learning_areas text[] not null default '{}',
  add column if not exists official_source_url text,
  add column if not exists storage_path text,
  add column if not exists file_type text not null default 'application/pdf',
  add column if not exists checksum text,
  add column if not exists version text,
  add column if not exists published_date date,
  add column if not exists catalogue_status text not null default 'needs_review'
    check (catalogue_status in ('current', 'needs_review', 'archived', 'unavailable'));

update public.learning_resources
set
  official_source_url = coalesce(official_source_url, source_url),
  book_number = coalesce(book_number, case when term is not null then 'Book ' || term::text end),
  learning_areas = case
    when resource_type = 'DBE Workbook' and cardinality(learning_areas) = 0
      then array['Home Language', 'Mathematics', 'Life Skills']::text[]
    when learning_area is not null and cardinality(learning_areas) = 0
      then array[learning_area]
    else learning_areas
  end,
  catalogue_status = case
    when resource_type <> 'DBE Workbook' then catalogue_status
    when status = 'archived' then 'archived'
    when source_url is null then 'unavailable'
    else catalogue_status
  end
where grade = 'Grade R';

create index if not exists learning_resources_workbook_catalogue_idx
  on public.learning_resources (academic_year desc, grade, language, term, catalogue_status)
  where resource_type = 'DBE Workbook';

create table if not exists public.learning_resource_years (
  id bigint generated by default as identity primary key,
  academic_year integer not null check (academic_year between 2000 and 2200),
  grade text not null default 'Grade R',
  is_default boolean not null default false,
  status text not null default 'needs_review'
    check (status in ('current', 'needs_review', 'archived', 'unavailable')),
  review_notes text,
  reviewed_at timestamptz,
  reviewed_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (academic_year, grade)
);

insert into public.learning_resource_years (academic_year, grade, is_default, status)
select distinct academic_year, grade, false,
  'needs_review'
from public.learning_resources
where academic_year is not null and grade = 'Grade R'
on conflict (academic_year, grade) do nothing;

update public.learning_resource_years
set is_default = true, updated_at = now()
where id = (
  select id from public.learning_resource_years
  where grade = 'Grade R' and status <> 'unavailable'
  order by academic_year desc limit 1
)
and not exists (
  select 1 from public.learning_resource_years
  where grade = 'Grade R' and is_default
);

create unique index if not exists learning_resource_years_one_default_grade_idx
  on public.learning_resource_years (grade) where is_default;

alter table public.learning_resource_years enable row level security;

alter table public.activity_learning_resources
  add column if not exists school_id bigint references public.schools(id) on delete cascade,
  add column if not exists classroom_id bigint references public.classrooms(id) on delete cascade,
  add column if not exists selected_pages integer[] not null default '{}',
  add column if not exists created_by uuid references auth.users(id) on delete set null;

alter table public.homework_learning_resources
  add column if not exists school_id bigint references public.schools(id) on delete cascade,
  add column if not exists classroom_id bigint references public.classrooms(id) on delete cascade,
  add column if not exists selected_pages integer[] not null default '{}',
  add column if not exists created_by uuid references auth.users(id) on delete set null;

update public.activity_learning_resources link
set school_id = plan.school_id,
    classroom_id = plan.classroom_id,
    selected_pages = case
      when cardinality(link.selected_pages) > 0 then link.selected_pages
      when link.page_from is not null then array(select generate_series(link.page_from, coalesce(link.page_to, link.page_from)))
      else '{}'::integer[]
    end
from public.weekly_activity_plans plan
where plan.id = link.weekly_plan_id
  and (link.school_id is null or link.classroom_id is null or cardinality(link.selected_pages) = 0);

update public.homework_learning_resources link
set school_id = assignment.school_id,
    classroom_id = assignment.classroom_id,
    selected_pages = case
      when cardinality(link.selected_pages) > 0 then link.selected_pages
      when link.page_from is not null then array(select generate_series(link.page_from, coalesce(link.page_to, link.page_from)))
      else '{}'::integer[]
    end
from public.homework_assignments assignment
where assignment.id = link.homework_assignment_id
  and (link.school_id is null or link.classroom_id is null or cardinality(link.selected_pages) = 0);

create index if not exists activity_learning_resources_school_idx
  on public.activity_learning_resources (school_id, classroom_id, weekly_plan_id);
create index if not exists homework_learning_resources_school_idx
  on public.homework_learning_resources (school_id, classroom_id, homework_assignment_id);

create or replace function public.validate_learning_resource_link_scope()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  expected_school_id bigint;
  expected_classroom_id bigint;
  resource_page_count integer;
begin
  if tg_table_name = 'activity_learning_resources' then
    select school_id, classroom_id into expected_school_id, expected_classroom_id
    from public.weekly_activity_plans where id = new.weekly_plan_id;
  else
    select school_id, classroom_id into expected_school_id, expected_classroom_id
    from public.homework_assignments where id = new.homework_assignment_id;
  end if;

  if expected_school_id is null or expected_classroom_id is null then
    raise exception 'The linked activity or homework assignment was not found.';
  end if;
  -- Populate the new scope columns for requests made by the immediately
  -- preceding application version during a migration/deployment window.
  new.school_id := coalesce(new.school_id, expected_school_id);
  new.classroom_id := coalesce(new.classroom_id, expected_classroom_id);
  if expected_school_id is distinct from new.school_id
     or expected_classroom_id is distinct from new.classroom_id then
    raise exception 'Learning resource links must match the school and classroom of their activity or homework.';
  end if;
  if cardinality(new.selected_pages) = 0 and new.page_from is not null
     and coalesce(new.page_to, new.page_from) >= new.page_from
     and coalesce(new.page_to, new.page_from) - new.page_from <= 1999 then
    new.selected_pages := array(
      select generate_series(new.page_from, coalesce(new.page_to, new.page_from))
    );
  end if;
  if exists (select 1 from unnest(new.selected_pages) page where page < 1) then
    raise exception 'Workbook page numbers must be positive.';
  end if;
  select resource.page_count into resource_page_count
  from public.learning_resources resource where resource.id = new.resource_id
    and (resource.school_id is null or resource.school_id = new.school_id);
  if not found then
    raise exception 'Resource belongs to another school.';
  end if;
  if resource_page_count is not null and exists (
    select 1 from unnest(new.selected_pages) page where page > resource_page_count
  ) then
    raise exception 'A selected page is outside the verified workbook page count.';
  end if;
  return new;
end;
$$;

drop trigger if exists activity_learning_resource_scope on public.activity_learning_resources;
create trigger activity_learning_resource_scope
before insert or update on public.activity_learning_resources
for each row execute function public.validate_learning_resource_link_scope();

drop trigger if exists homework_learning_resource_scope on public.homework_learning_resources;
create trigger homework_learning_resource_scope
before insert or update on public.homework_learning_resources
for each row execute function public.validate_learning_resource_link_scope();

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('dbe-workbooks', 'dbe-workbooks', false, 104857600, array['application/pdf']::text[])
on conflict (id) do update set
  public = false,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

comment on table public.learning_resource_years is
  'Master-reviewed academic-year catalogue state. One default year is allowed per grade.';
comment on column public.learning_resources.learning_areas is
  'Search metadata for an integrated workbook; it does not create separate workbook editions.';
comment on column public.learning_resources.storage_path is
  'Optional private dbe-workbooks object path. The official source URL remains retained separately.';

-- Access remains through authenticated API handlers. No anonymous/authenticated
-- storage-object policies are introduced for the workbook bucket.
revoke all on public.learning_resource_years from anon, authenticated;
grant all on public.learning_resource_years to service_role;

create or replace function public.set_learning_resource_default_year(target_year integer, actor uuid)
returns void language plpgsql security definer set search_path = public as $$
begin
  perform pg_advisory_xact_lock(hashtext('grade-r-default-year'));
  if not exists (select 1 from public.learning_resources where academic_year = target_year
      and grade = 'Grade R' and status = 'published' and catalogue_status = 'current'
      and storage_path is not null) then
    raise exception 'Publish a verified workbook before making this year current.';
  end if;
  if not exists (select 1 from public.learning_resource_years where academic_year = target_year and grade = 'Grade R') then
    raise exception 'Academic year was not found.';
  end if;
  update public.learning_resource_years set is_default = false where grade = 'Grade R' and is_default;
  update public.learning_resource_years set is_default = true, status = 'current',
    reviewed_at = now(), reviewed_by = actor, updated_at = now()
    where academic_year = target_year and grade = 'Grade R';
end;
$$;
revoke all on function public.set_learning_resource_default_year(integer, uuid) from public, anon, authenticated;
grant execute on function public.set_learning_resource_default_year(integer, uuid) to service_role;

create table if not exists public.learning_resource_file_history (
  id bigint generated by default as identity primary key,
  resource_id bigint not null references public.learning_resources(id) on delete restrict,
  storage_path text not null,
  checksum text,
  version text,
  page_count integer,
  recorded_at timestamptz not null default now()
);
alter table public.learning_resource_file_history enable row level security;
revoke all on public.learning_resource_file_history from anon, authenticated;
grant all on public.learning_resource_file_history to service_role;
create or replace function public.retain_learning_resource_file_history()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if old.storage_path is not null and old.storage_path is distinct from new.storage_path then
    insert into public.learning_resource_file_history(resource_id, storage_path, checksum, version, page_count)
      values(old.id, old.storage_path, old.checksum, old.version, old.page_count);
  end if;
  return new;
end;
$$;
drop trigger if exists learning_resource_file_history on public.learning_resources;
create trigger learning_resource_file_history before update of storage_path on public.learning_resources
  for each row execute function public.retain_learning_resource_file_history();

create or replace function public.review_learning_resource_update(review_id bigint, decision text, actor uuid)
returns void language plpgsql security definer set search_path = public as $$
declare review public.learning_resource_update_reviews%rowtype;
begin
  if decision not in ('approved','rejected') then raise exception 'Invalid decision.'; end if;
  select * into review from public.learning_resource_update_reviews where id = review_id and status = 'pending' for update;
  if review.id is null then raise exception 'Review is no longer pending.'; end if;
  if decision = 'approved' then
    insert into public.learning_resources(title, grade, resource_type, source_name, source_url,
      official_source_url, academic_year, language, term, book_number, learning_areas,
      status, catalogue_status, content_rights, is_parent_shareable, created_by)
    values(review.title, review.grade, 'DBE Workbook', review.source_name, review.source_url,
      review.source_url, review.academic_year, review.proposed_resource->>'language',
      nullif(review.proposed_resource->>'term','')::smallint,
      'Book ' || (review.proposed_resource->>'term'), array['Home Language','Mathematics','Life Skills'],
      'draft', 'needs_review', 'DBE State-Owned', true, actor);
    insert into public.learning_resource_years(academic_year, grade) values(review.academic_year, review.grade)
      on conflict(academic_year,grade) do nothing;
  end if;
  update public.learning_resource_update_reviews set status = decision, reviewed_at = now(), reviewed_by = actor where id = review_id;
end;
$$;
revoke all on function public.review_learning_resource_update(bigint,text,uuid) from public, anon, authenticated;
grant execute on function public.review_learning_resource_update(bigint,text,uuid) to service_role;

commit;
