-- Controlled learner-account reconciliation. This remains separate from
-- DailyBloom's own subscription billing journal.

alter table public.learner_fee_charges
  add column if not exists is_scheduled boolean not null default false;

alter table public.learner_fee_payments
  add column if not exists entry_source text not null default 'payment',
  add column if not exists allocation_period date;

create table if not exists public.learner_fee_journal_entries (
  id bigint generated by default as identity primary key,
  school_id bigint not null references public.schools(id) on delete cascade,
  learner_id uuid not null references public.learners(id) on delete cascade,
  entry_type text not null check (entry_type in ('debit', 'credit')),
  entry_scope text not null check (entry_scope in ('opening_balance', 'monthly_fee', 'registration_fee', 'correction')),
  amount numeric(12,2) not null check (amount > 0),
  effective_date date not null,
  allocation_period date,
  reason text not null check (length(trim(reason)) >= 3),
  charge_id bigint references public.learner_fee_charges(id) on delete restrict,
  payment_id bigint references public.learner_fee_payments(id) on delete restrict,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  check (
    (entry_type = 'debit' and charge_id is not null and payment_id is null)
    or (entry_type = 'credit' and payment_id is not null and charge_id is null)
  )
);

create index if not exists learner_fee_journal_entries_account_idx
  on public.learner_fee_journal_entries(school_id, learner_id, effective_date, id);

alter table public.learner_fee_journal_entries enable row level security;

-- Journals are an audit trail: corrections are recorded as a new entry, never
-- by changing or deleting the original entry.
create or replace function public.prevent_learner_fee_journal_mutation()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  raise exception 'Learner fee journal entries are immutable. Record a correcting journal entry instead.';
end;
$$;

drop trigger if exists learner_fee_journal_entries_immutable on public.learner_fee_journal_entries;
create trigger learner_fee_journal_entries_immutable
before update or delete on public.learner_fee_journal_entries
for each row execute function public.prevent_learner_fee_journal_mutation();

-- A pre-created annual plan becomes a normal posted charge at the start of
-- that month, so the scheduled future months never inflate today's balance.
create or replace function public.generate_learner_monthly_fee_charges(
  target_date date default current_date
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  month_start date := date_trunc('month', target_date)::date;
  inserted_count integer := 0;
begin
  update public.learner_fee_charges
  set is_scheduled = false
  where charge_type = 'monthly_fee'
    and billing_period = month_start
    and is_scheduled = true;

  insert into public.learner_fee_charges (
    school_id, learner_id, charge_type, description, billing_period,
    due_date, amount, is_scheduled
  )
  select
    learner.school_id,
    learner.id,
    'monthly_fee',
    'School fees - ' || to_char(month_start, 'FMMonth YYYY'),
    month_start,
    month_start,
    learner.monthly_fee,
    false
  from public.learners learner
  where coalesce(learner.is_deleted, false) = false
    and learner.school_id is not null
    and learner.monthly_fee > 0
    and learner.fee_billing_start_date <= month_start
  on conflict (school_id, learner_id, charge_type, billing_period)
  do nothing;

  get diagnostics inserted_count = row_count;
  return inserted_count;
end;
$$;

revoke all on function public.generate_learner_monthly_fee_charges(date) from public;
grant execute on function public.generate_learner_monthly_fee_charges(date) to service_role;
