create table if not exists public.learner_progress_reviews (
  id bigint generated by default as identity primary key,
  school_id bigint not null references public.schools(id) on delete cascade,
  classroom_id bigint not null references public.classrooms(id) on delete cascade,
  learner_id uuid not null references public.learners(id) on delete cascade,
  report_period_id bigint references public.report_periods(id) on delete set null,
  review_date date not null default current_date,
  discussion_summary text not null,
  agreed_actions text,
  home_support text,
  next_review_date date,
  recorded_by uuid references auth.users(id) on delete set null,
  recorded_by_name text,
  created_at timestamptz not null default now()
);

create index if not exists learner_progress_reviews_school_learner_date_idx
  on public.learner_progress_reviews (school_id, learner_id, review_date desc, created_at desc);

alter table public.learner_progress_reviews enable row level security;

comment on table public.learner_progress_reviews is
  'An append-only, parent-meeting-friendly learner development review history. Access is mediated by the authorised server API.';
