create table if not exists impact_training_records (
  id bigint generated by default as identity primary key,
  school_id bigint not null references schools(id),
  training_date date not null,
  training_type text not null,
  attendees_count integer default 0,
  notes text,
  created_at timestamp with time zone default now()
);

create table if not exists impact_success_stories (
  id bigint generated by default as identity primary key,
  school_id bigint not null references schools(id),
  story_date date not null,
  title text not null,
  summary text,
  outcome text,
  created_at timestamp with time zone default now()
);
