create table if not exists public.parent_permission_requests (
  id bigint generated by default as identity primary key,
  school_id bigint not null references public.schools(id) on delete cascade,
  permission_type text not null check (permission_type in ('photos_videos', 'general', 'school_excursion')),
  title text not null,
  description text not null,
  event_date date,
  response_deadline date,
  status text not null default 'sent' check (status in ('draft', 'sent', 'closed')),
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.parent_permission_request_learners (
  request_id bigint not null references public.parent_permission_requests(id) on delete cascade,
  learner_id uuid not null references public.learners(id) on delete cascade,
  school_id bigint not null references public.schools(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (request_id, learner_id)
);

create table if not exists public.parent_permission_responses (
  request_id bigint not null references public.parent_permission_requests(id) on delete cascade,
  learner_id uuid not null references public.learners(id) on delete cascade,
  school_id bigint not null references public.schools(id) on delete cascade,
  response text not null check (response in ('granted', 'declined')),
  parent_name text not null,
  parent_phone text,
  responded_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (request_id, learner_id)
);

create index if not exists parent_permission_requests_school_created_idx
  on public.parent_permission_requests (school_id, created_at desc);
create index if not exists parent_permission_request_learners_learner_idx
  on public.parent_permission_request_learners (learner_id, request_id);
create index if not exists parent_permission_responses_school_idx
  on public.parent_permission_responses (school_id, request_id);

alter table public.parent_permission_requests enable row level security;
alter table public.parent_permission_request_learners enable row level security;
alter table public.parent_permission_responses enable row level security;

comment on table public.parent_permission_requests is
  'School-created consent requests. Parent access is served through authenticated server routes.';
comment on table public.parent_permission_responses is
  'Learner-specific, auditable parent decisions for consent requests.';
