-- Auditable setup-fee exemptions.
-- Run after 20260724_billing_invoice_ledger.sql.

alter table public.billing_invoices
  add column if not exists exemption_reason text,
  add column if not exists exempted_at timestamptz,
  add column if not exists exempted_by uuid references public.profiles(id) on delete set null;

create table if not exists public.billing_journal_entries (
  id bigint generated by default as identity primary key,
  school_id bigint not null references public.schools(id) on delete restrict,
  invoice_id uuid references public.billing_invoices(id) on delete restrict,
  entry_type text not null check (entry_type in ('setup_fee_exemption')),
  amount numeric(12,2) not null check (amount >= 0),
  reason text not null check (char_length(trim(reason)) >= 3),
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create unique index if not exists billing_setup_exemption_once_idx
  on public.billing_journal_entries (invoice_id, entry_type)
  where invoice_id is not null and entry_type = 'setup_fee_exemption';

create index if not exists billing_journal_school_created_idx
  on public.billing_journal_entries (school_id, created_at desc);

alter table public.billing_journal_entries enable row level security;
grant select on public.billing_journal_entries to authenticated;

drop policy if exists "Billing journal school read"
  on public.billing_journal_entries;
create policy "Billing journal school read"
on public.billing_journal_entries for select to authenticated
using (
  public.current_platform_has_permission('billing.manage')
  or exists (
    select 1
    from public.profiles profile
    where profile.id = auth.uid()
      and profile.school_id = billing_journal_entries.school_id
      and profile.is_active is distinct from false
      and profile.role in ('owner', 'principal')
  )
  or exists (
    select 1
    from public.school_memberships membership
    where membership.user_id = auth.uid()
      and membership.school_id = billing_journal_entries.school_id
      and membership.status = 'active'
      and (
        membership.role in ('owner', 'principal')
        or 'billing.manage' = any(coalesce(membership.permissions, '{}'::text[]))
      )
  )
);

comment on table public.billing_journal_entries is
  'Immutable audit journal for billing adjustments such as setup-fee exemptions.';

create or replace function public.apply_setup_fee_exemption(
  target_school_id bigint,
  exemption_reason text,
  actor_id uuid
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  target_invoice public.billing_invoices%rowtype;
begin
  if char_length(trim(coalesce(exemption_reason, ''))) < 3 then
    raise exception 'An exemption reason of at least 3 characters is required.';
  end if;

  select *
    into target_invoice
    from public.billing_invoices
   where school_id = target_school_id
     and charge_type = 'setup_fee'
   for update;

  if target_invoice.id is null then
    raise exception 'The setup-fee invoice was not found.';
  end if;
  if target_invoice.exempted_at is not null then
    return target_invoice.id;
  end if;
  if target_invoice.amount_paid > 0 or exists (
    select 1
      from public.billing_payment_allocations allocation
     where allocation.invoice_id = target_invoice.id
  ) then
    raise exception 'A setup fee with recorded payments cannot be exempted.';
  end if;

  update public.billing_invoices
     set description = description || ' — Setup fee exempted',
         subtotal = 0,
         total_amount = 0,
         amount_paid = 0,
         balance_due = 0,
         status = 'paid',
         exemption_reason = trim(exemption_reason),
         exempted_at = now(),
         exempted_by = actor_id,
         updated_at = now()
   where id = target_invoice.id;

  insert into public.billing_journal_entries (
    school_id,
    invoice_id,
    entry_type,
    amount,
    reason,
    created_by
  )
  values (
    target_school_id,
    target_invoice.id,
    'setup_fee_exemption',
    target_invoice.total_amount,
    trim(exemption_reason),
    actor_id
  )
  on conflict (invoice_id, entry_type)
  where invoice_id is not null and entry_type = 'setup_fee_exemption'
  do nothing;

  return target_invoice.id;
end;
$$;

revoke all on function public.apply_setup_fee_exemption(bigint, text, uuid)
  from public, anon, authenticated;
grant execute on function public.apply_setup_fee_exemption(bigint, text, uuid)
  to service_role;
