create table if not exists public.learning_resources (
  id bigint generated by default as identity primary key,
  school_id bigint references public.schools(id) on delete cascade,
  title text not null,
  description text,
  grade text not null default 'Grade R',
  resource_type text not null,
  source_name text,
  source_url text,
  language text,
  term smallint check (term between 1 and 4),
  week_from smallint check (week_from between 1 and 40),
  week_to smallint check (week_to between 1 and 40),
  learning_area text,
  topic text,
  themes text[] not null default '{}',
  page_count integer,
  content_rights text not null default 'Unknown / Review Required',
  is_downloadable boolean not null default false,
  is_printable boolean not null default false,
  is_parent_shareable boolean not null default false,
  status text not null default 'draft' check (status in ('draft','published','archived')),
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists learning_resources_grade_status_idx on public.learning_resources (grade, status, term, week_from);
create index if not exists learning_resources_school_idx on public.learning_resources (school_id);

create table if not exists public.activity_learning_resources (
  id bigint generated by default as identity primary key,
  weekly_plan_id bigint not null references public.weekly_activity_plans(id) on delete cascade,
  resource_id bigint not null references public.learning_resources(id) on delete restrict,
  page_from integer check (page_from > 0),
  page_to integer check (page_to > 0 and page_to >= page_from),
  created_at timestamptz not null default now(),
  unique (weekly_plan_id, resource_id, page_from, page_to)
);

create table if not exists public.homework_learning_resources (
  id bigint generated by default as identity primary key,
  homework_assignment_id bigint not null references public.homework_assignments(id) on delete cascade,
  resource_id bigint not null references public.learning_resources(id) on delete restrict,
  page_from integer check (page_from > 0),
  page_to integer check (page_to > 0 and page_to >= page_from),
  created_at timestamptz not null default now(),
  unique (homework_assignment_id, resource_id, page_from, page_to)
);

alter table public.learning_resources enable row level security;
alter table public.activity_learning_resources enable row level security;
alter table public.homework_learning_resources enable row level security;
