-- Preschool-to-parent fee accounts, separate from platform subscriptions.
create table if not exists public.learner_fee_charges (
  id bigint generated by default as identity primary key,
  school_id bigint not null references public.schools(id) on delete cascade,
  learner_id uuid not null references public.learners(id) on delete cascade,
  charge_type text not null default 'monthly_fee',
  description text not null,
  billing_period date not null,
  due_date date not null,
  amount numeric(12,2) not null check (amount >= 0),
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  unique (school_id, learner_id, charge_type, billing_period)
);

create table if not exists public.learner_fee_payments (
  id bigint generated by default as identity primary key,
  school_id bigint not null references public.schools(id) on delete cascade,
  learner_id uuid not null references public.learners(id) on delete cascade,
  amount numeric(12,2) not null check (amount > 0),
  payment_date date not null,
  payment_method text not null,
  reference_number text,
  receipt_number text not null unique,
  parent_portal_published_at timestamptz not null default now(),
  recorded_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.learner_fee_allocations (
  id bigint generated by default as identity primary key,
  payment_id bigint not null references public.learner_fee_payments(id) on delete restrict,
  charge_id bigint not null references public.learner_fee_charges(id) on delete restrict,
  amount numeric(12,2) not null check (amount > 0),
  created_at timestamptz not null default now(),
  unique (payment_id, charge_id)
);

create index if not exists learner_fee_charges_account_idx
  on public.learner_fee_charges(school_id, learner_id, billing_period, id);
create index if not exists learner_fee_payments_account_idx
  on public.learner_fee_payments(school_id, learner_id, payment_date, id);
create index if not exists learner_fee_allocations_charge_idx
  on public.learner_fee_allocations(charge_id);

alter table public.learner_fee_charges enable row level security;
alter table public.learner_fee_payments enable row level security;
alter table public.learner_fee_allocations enable row level security;

-- Access is intentionally server-route only. No direct browser policies.
