create table if not exists public.learning_resource_update_reviews (
  id bigint generated by default as identity primary key,
  title text not null,
  grade text not null default 'Grade R',
  source_name text not null,
  source_url text not null,
  academic_year integer not null,
  review_notes text,
  proposed_resource jsonb not null default '{}'::jsonb,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  detected_at timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewed_by uuid references auth.users(id) on delete set null
);

create index if not exists learning_resource_update_reviews_status_idx
  on public.learning_resource_update_reviews (status, academic_year, detected_at desc);

alter table public.learning_resource_update_reviews enable row level security;
