-- Master billing controls for DailyBloom's own preschool subscriptions.
-- These controls deliberately do not touch learner-fee billing or parent statements.

alter table public.schools
  add column if not exists is_demo_school boolean not null default false,
  add column if not exists demo_school_reason text,
  add column if not exists demo_school_set_at timestamptz,
  add column if not exists demo_school_set_by uuid references public.profiles(id) on delete set null;

update public.schools
set is_demo_school = false
where is_demo_school is null;

comment on column public.schools.is_demo_school is
  'When true, the school remains usable but DailyBloom setup fees, recurring subscriptions, payment reminders and payment recording are disabled.';

-- Allow a debit journal to be represented by a durable invoice charge and a
-- credit journal to be represented by an auditable non-cash payment credit.
do $$
declare
  constraint_name text;
begin
  for constraint_name in
    select constraint_record.conname
    from pg_constraint constraint_record
    where constraint_record.conrelid = 'public.billing_invoices'::regclass
      and constraint_record.contype = 'c'
      and pg_get_constraintdef(constraint_record.oid) ilike '%charge_type%'
  loop
    execute format(
      'alter table public.billing_invoices drop constraint if exists %I',
      constraint_name
    );
  end loop;

  alter table public.billing_invoices
    add constraint billing_invoices_charge_type_check
    check (charge_type in ('setup_fee', 'subscription', 'debit_journal'));
end;
$$;

do $$
declare
  constraint_name text;
begin
  for constraint_name in
    select constraint_record.conname
    from pg_constraint constraint_record
    where constraint_record.conrelid = 'public.subscription_payments'::regclass
      and constraint_record.contype = 'c'
      and pg_get_constraintdef(constraint_record.oid) ilike '%charge_type%'
  loop
    execute format(
      'alter table public.subscription_payments drop constraint if exists %I',
      constraint_name
    );
  end loop;

  alter table public.subscription_payments
    add constraint subscription_payments_charge_type_check
    check (charge_type in ('setup_fee', 'subscription', 'credit_journal'));
end;
$$;

alter table public.billing_journal_entries
  add column if not exists payment_id bigint references public.subscription_payments(id) on delete restrict,
  add column if not exists effective_date date;

update public.billing_journal_entries
set effective_date = created_at::date
where effective_date is null;

alter table public.billing_journal_entries
  alter column effective_date set not null;

do $$
declare
  constraint_name text;
begin
  for constraint_name in
    select constraint_record.conname
    from pg_constraint constraint_record
    where constraint_record.conrelid = 'public.billing_journal_entries'::regclass
      and constraint_record.contype = 'c'
      and pg_get_constraintdef(constraint_record.oid) ilike '%entry_type%'
  loop
    execute format(
      'alter table public.billing_journal_entries drop constraint if exists %I',
      constraint_name
    );
  end loop;

  alter table public.billing_journal_entries
    add constraint billing_journal_entries_entry_type_check
    check (entry_type in ('setup_fee_exemption', 'credit_journal', 'debit_journal'));
end;
$$;

create index if not exists billing_journal_school_effective_idx
  on public.billing_journal_entries (school_id, effective_date desc, id desc);

create table if not exists public.billing_payment_reminders (
  id bigint generated by default as identity primary key,
  school_id bigint not null references public.schools(id) on delete restrict,
  subscription_id bigint not null references public.school_subscriptions(id) on delete restrict,
  phone_number text not null,
  message text not null check (char_length(trim(message)) >= 8),
  provider_message_id text,
  sent_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists billing_payment_reminders_school_created_idx
  on public.billing_payment_reminders (school_id, created_at desc);

alter table public.billing_payment_reminders enable row level security;
revoke all on public.billing_payment_reminders from public, anon, authenticated;
grant all on public.billing_payment_reminders to service_role;

create or replace function public.set_dailybloom_demo_school(
  target_school_id bigint,
  demo_reason text,
  actor_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  target_school public.schools%rowtype;
begin
  if char_length(trim(coalesce(demo_reason, ''))) < 3 then
    raise exception 'A demo-school reason of at least 3 characters is required.';
  end if;

  select *
    into target_school
    from public.schools
   where id = target_school_id
   for update;

  if target_school.id is null then
    raise exception 'School % was not found.', target_school_id;
  end if;

  update public.schools
     set is_demo_school = true,
         demo_school_reason = trim(demo_reason),
         demo_school_set_at = now(),
         demo_school_set_by = actor_id,
         updated_at = now()
   where id = target_school_id;

  update public.school_subscriptions
     set next_billing_date = null,
         updated_at = now()
   where school_id = target_school_id;

  return jsonb_build_object(
    'school_id', target_school_id,
    'is_demo_school', true,
    'message', 'DailyBloom billing is paused for this Demo school.'
  );
end;
$$;

revoke all on function public.set_dailybloom_demo_school(bigint, text, uuid)
  from public, anon, authenticated;
grant execute on function public.set_dailybloom_demo_school(bigint, text, uuid)
  to service_role;

create or replace function public.post_school_billing_journal(
  target_school_id bigint,
  target_subscription_id bigint,
  journal_type text,
  journal_amount numeric,
  effective_on date,
  journal_reason text,
  actor_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  target_school public.schools%rowtype;
  target_subscription public.school_subscriptions%rowtype;
  new_invoice_id uuid;
  new_payment_id bigint;
  new_journal_id bigint;
  record_key text;
  reconciliation jsonb;
begin
  if journal_type not in ('credit', 'debit') then
    raise exception 'Journal type must be credit or debit.';
  end if;
  if coalesce(journal_amount, 0) <= 0 then
    raise exception 'Journal amount must be greater than zero.';
  end if;
  if effective_on is null or effective_on > current_date then
    raise exception 'Journal effective date cannot be in the future.';
  end if;
  if char_length(trim(coalesce(journal_reason, ''))) < 3 then
    raise exception 'A journal reason of at least 3 characters is required.';
  end if;

  select *
    into target_school
    from public.schools
   where id = target_school_id
   for update;
  if target_school.id is null then
    raise exception 'School % was not found.', target_school_id;
  end if;
  if target_school.is_demo_school then
    raise exception 'Demo schools do not have DailyBloom billing journals.';
  end if;

  select *
    into target_subscription
    from public.school_subscriptions
   where id = target_subscription_id
     and school_id = target_school_id
   for update;
  if target_subscription.id is null then
    raise exception 'Subscription was not found for this school.';
  end if;

  reconciliation := public.reconcile_school_billing_account(target_school_id, 599);
  record_key := upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 8));

  if journal_type = 'credit' then
    insert into public.subscription_payments (
      school_id,
      subscription_id,
      amount,
      original_amount,
      unapplied_amount,
      payment_date,
      charge_type,
      plan_name,
      payment_method,
      notes,
      receipt_number
    )
    values (
      target_school_id,
      target_subscription.id,
      journal_amount,
      journal_amount,
      journal_amount,
      effective_on,
      'credit_journal',
      target_subscription.plan_name,
      'Journal Credit',
      'Journal credit: ' || trim(journal_reason),
      'DB-JRN-' || to_char(effective_on, 'YYYYMMDD') || '-' || record_key
    )
    returning id into new_payment_id;

    -- The normal payment trigger queues receipts. A journal is an internal
    -- adjustment, so it must not generate an automatic customer email.
    delete from public.billing_email_outbox
     where payment_id = new_payment_id
       and email_type = 'payment_receipt';

    insert into public.billing_journal_entries (
      school_id,
      payment_id,
      entry_type,
      amount,
      reason,
      created_by,
      effective_date
    )
    values (
      target_school_id,
      new_payment_id,
      'credit_journal',
      journal_amount,
      trim(journal_reason),
      actor_id,
      effective_on
    )
    returning id into new_journal_id;
  else
    insert into public.billing_invoices (
      school_id,
      subscription_id,
      invoice_number,
      external_key,
      charge_type,
      description,
      plan_name,
      issue_date,
      due_date,
      subtotal,
      vat_amount,
      total_amount,
      amount_paid,
      balance_due,
      status
    )
    values (
      target_school_id,
      target_subscription.id,
      'DB-JRN-' || to_char(effective_on, 'YYYYMMDD') || '-' || target_school_id || '-' || record_key,
      'debit-journal:' || target_school_id || ':' || gen_random_uuid()::text,
      'debit_journal',
      'Manual debit journal - ' || trim(journal_reason),
      target_subscription.plan_name,
      effective_on,
      effective_on,
      journal_amount,
      0,
      journal_amount,
      0,
      journal_amount,
      'issued'
    )
    returning id into new_invoice_id;

    insert into public.billing_journal_entries (
      school_id,
      invoice_id,
      entry_type,
      amount,
      reason,
      created_by,
      effective_date
    )
    values (
      target_school_id,
      new_invoice_id,
      'debit_journal',
      journal_amount,
      trim(journal_reason),
      actor_id,
      effective_on
    )
    returning id into new_journal_id;
  end if;

  reconciliation := public.reconcile_school_billing_account(target_school_id, 599);

  return jsonb_build_object(
    'school_id', target_school_id,
    'journal_id', new_journal_id,
    'invoice_id', new_invoice_id,
    'payment_id', new_payment_id,
    'journal_type', journal_type,
    'amount', journal_amount,
    'reconciliation', reconciliation
  );
end;
$$;

revoke all on function public.post_school_billing_journal(bigint, bigint, text, numeric, date, text, uuid)
  from public, anon, authenticated;
grant execute on function public.post_school_billing_journal(bigint, bigint, text, numeric, date, text, uuid)
  to service_role;

comment on function public.post_school_billing_journal(bigint, bigint, text, numeric, date, text, uuid) is
  'Posts a Master-only DailyBloom subscription credit or debit journal and reconciles the affected preschool account.';
