-- DailyBloom invoice ledger.
-- Keeps existing school_subscriptions and subscription_payments intact while
-- adding immutable monthly/setup charges and explicit payment allocations.

create extension if not exists pgcrypto;

create table if not exists public.billing_invoices (
  id uuid primary key default gen_random_uuid(),
  school_id bigint not null references public.schools(id) on delete restrict,
  subscription_id bigint references public.school_subscriptions(id) on delete set null,
  invoice_number text not null unique,
  external_key text not null unique,
  charge_type text not null check (charge_type in ('setup_fee', 'subscription')),
  description text not null,
  plan_name text,
  issue_date date not null,
  due_date date not null,
  period_start date,
  period_end date,
  subtotal numeric(12,2) not null check (subtotal >= 0),
  vat_amount numeric(12,2) not null default 0 check (vat_amount = 0),
  total_amount numeric(12,2) not null check (total_amount >= 0),
  amount_paid numeric(12,2) not null default 0 check (amount_paid >= 0),
  balance_due numeric(12,2) not null check (balance_due >= 0),
  status text not null default 'issued'
    check (status in ('issued', 'partially_paid', 'paid', 'void')),
  download_token uuid not null default gen_random_uuid() unique,
  emailed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists billing_invoices_school_issue_idx
  on public.billing_invoices (school_id, issue_date desc);
create index if not exists billing_invoices_open_idx
  on public.billing_invoices (school_id, due_date)
  where status in ('issued', 'partially_paid');
create index if not exists billing_invoices_period_idx
  on public.billing_invoices (period_start, period_end)
  where charge_type = 'subscription';

alter table public.subscription_payments
  add column if not exists unapplied_amount numeric(12,2) not null default 0;

create table if not exists public.billing_payment_allocations (
  id bigint generated by default as identity primary key,
  payment_id bigint not null references public.subscription_payments(id) on delete restrict,
  invoice_id uuid not null references public.billing_invoices(id) on delete restrict,
  amount numeric(12,2) not null check (amount > 0),
  created_at timestamptz not null default now(),
  unique (payment_id, invoice_id)
);

create index if not exists billing_allocations_invoice_idx
  on public.billing_payment_allocations (invoice_id);
create index if not exists billing_allocations_payment_idx
  on public.billing_payment_allocations (payment_id);

alter table public.billing_invoices enable row level security;
alter table public.billing_payment_allocations enable row level security;

grant select on public.billing_invoices to authenticated;
grant select on public.billing_payment_allocations to authenticated;

drop policy if exists "Billing invoice school read" on public.billing_invoices;
create policy "Billing invoice school read"
on public.billing_invoices for select to authenticated
using (
  public.current_platform_has_permission('billing.manage')
  or exists (
    select 1
    from public.profiles profile
    where profile.id = auth.uid()
      and profile.school_id = billing_invoices.school_id
      and profile.is_active is distinct from false
      and profile.role in ('owner', 'principal')
  )
  or exists (
    select 1
    from public.school_memberships membership
    where membership.user_id = auth.uid()
      and membership.school_id = billing_invoices.school_id
      and membership.status = 'active'
      and (
        membership.role in ('owner', 'principal')
        or 'billing.manage' = any(coalesce(membership.permissions, '{}'::text[]))
      )
  )
);

drop policy if exists "Billing allocation school read" on public.billing_payment_allocations;
create policy "Billing allocation school read"
on public.billing_payment_allocations for select to authenticated
using (
  exists (
    select 1
    from public.billing_invoices invoice
    where invoice.id = billing_payment_allocations.invoice_id
  )
);

comment on table public.billing_invoices is
  'Setup and monthly DailyBloom subscription charges. Historical package names and prices are snapshots.';
comment on column public.billing_invoices.external_key is
  'Idempotency key preventing duplicate setup or monthly subscription invoices.';
comment on column public.subscription_payments.unapplied_amount is
  'Payment credit remaining after allocation to the oldest outstanding invoices.';
