"use client";
import { FormEvent, useEffect, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { getCurrentProfile } from "@/app/lib/auth";
import { resolveSchoolContext } from "@/app/lib/school-context";
import { authenticatedFetch } from "@/app/lib/authenticated-fetch";
import { ComplianceHeader } from "../components";
type Item=Record<string,unknown>;
export default function InspectionsPage(){const router=useRouter(),params=useSearchParams();const[school,setSchool]=useState<number>();const[inspections,setInspections]=useState<Item[]>([]),[findings,setFindings]=useState<Item[]>([]),[open,setOpen]=useState<string>(),[saving,setSaving]=useState(false);
const load=async(id:number)=>{const[a,b]=await Promise.all([authenticatedFetch(`/api/compliance?school_id=${id}&resource=inspections`).then(r=>r.json()),authenticatedFetch(`/api/compliance?school_id=${id}&resource=findings`).then(r=>r.json())]);setInspections(a.items||[]);setFindings(b.items||[])};
useEffect(()=>{void(async()=>{const{profile}=await getCurrentProfile();if(!profile||profile.role==="teacher"){router.replace(profile?"/teacher":"/login");return}const c=await resolveSchoolContext(params.get("school"));if(!c.schoolId){router.replace("/login");return}setSchool(c.schoolId);await load(c.schoolId)})()},[params,router]);
const submit=async(resource:string,e:FormEvent<HTMLFormElement>,more:Record<string,unknown>={})=>{e.preventDefault();if(!school)return;setSaving(true);const f=new FormData(e.currentTarget);const body=Object.fromEntries(f);const r=await authenticatedFetch("/api/compliance",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({school_id:school,resource,...body,...more})});if(!r.ok)alert((await r.json()).error||"Could not save.");else{e.currentTarget.reset();await load(school)}setSaving(false)};
const makeAction=(finding:Item)=>{if(!school)return;router.push(`/dbe-registration/corrective-actions?school=${school}&source_type=inspection_finding&source_id=${encodeURIComponent(String(finding.id))}`)};
if(!school)return <p>Loading inspections...</p>;return <div><ComplianceHeader title="Inspections" description="Record school/internal and external inspections separately. School entries are not official DBE findings."/><div className="db-card db-card-blue" style={{padding:16,marginBottom:14}}><h3>Add inspection</h3><form onSubmit={e=>void submit("inspections",e)} style={{display:"grid",gap:8}}><input className="db-input" required name="inspection_type" placeholder="Inspection type"/><select className="db-input" name="inspection_scope"><option>Internal</option><option>External / Official</option></select><input className="db-input" type="date" name="scheduled_date"/><button className="db-button-primary" disabled={saving}>Save inspection</button></form></div>{inspections.length===0?<p className="db-helper">No inspections have been recorded yet.</p>:inspections.map(i=>{const these=findings.filter(f=>f.inspection_id===i.id);return <div key={String(i.id)} className="db-card db-card-lavender" style={{padding:16,marginBottom:12}}><button className="db-button-secondary" onClick={()=>setOpen(open===i.id?undefined:String(i.id))}>{open===i.id?"Close findings":"Open findings"}</button><h3>{String(i.inspection_type)}</h3><p className="db-helper">{String(i.inspection_scope)} · {String(i.status)}</p>{open===i.id?<><h4>Findings ({these.length})</h4>{these.map(f=><div className="db-list-card" key={String(f.id)}><strong>{String(f.category||"Finding")}</strong><p>{String(f.description)}</p><p className="db-helper">{String(f.priority)} · {String(f.status)}</p>{f.corrective_action_required?<button className="db-button-secondary" onClick={()=>void makeAction(f)}>Create corrective action</button>:null}</div>)}<form onSubmit={e=>void submit("findings",e,{inspection_id:i.id})} style={{display:"grid",gap:8,marginTop:10}}><input className="db-input" name="category" placeholder="Category"/><textarea className="db-input" required name="description" placeholder="What was found?"/><select className="db-input" name="priority"><option>Normal</option><option>Low</option><option>High</option></select><label><input type="checkbox" name="corrective_action_required"/> Corrective action required</label><button className="db-button-primary" disabled={saving}>Add finding</button></form></>:null}</div>})}</div>}
